# What is the Endogenous Personality?

What is the Endogenous Personality? And why is he so important?
In a nutshell, we argue that the Endogenous personality is the type of a potential genius – a compound of abilities and attitudes, of intelligence and innerness. As a strong generalization: the true geniuses are Endogenous personalities; and it is from Endogenous personalities that geniuses arise.

The Endogenous personality is the ‘inner’ Man; a person whose outlook on life is ‘inward.’ He is inner-directed, inner-driven, inner-motivated; one who uses inner modes of thinking, inner evaluations, in-tuition; one who is to a high degree autonomous, self-sufficient; one who is relatively indifferent to social pressures, influences and inducements.
He stands in stark contrast to the Exogenous personality; that is, to most people. The Exogenous Personality is orientated toward the environment, particularly the social environment. These are people who want more than anything else social (including sexual) status, worldly success; people whose perceptions are directed outwards and who try to align their behaviour with group norms.

When described in such terms, the Endogenous personality might appear anti-social, uncooperative, a dreamer, not the kind of person we might wish to have to deal with on a regular basis. We would probably be accurate in perceiving the Endogenous Personality in this negative way. We probably wouldn’t want to go for a drink with him, let alone be friends with him.

But he is important; he is very important. Because the Endogenous personality is the archetypal ‘genius.’ He is the *type* of a genius – whether a large scale, world historical genius of the highest level achieved by humanity – a Shakespeare, a Beethoven or an Einstein – or a local, tribal, or town genius; a shaman, a sculptor, an inventor whose name is unrecorded (yet who might be the originator of some great but anonymous ballad, folk song, painting -- or a technological breakthrough such as the spade, spear-thrower, arch or stirrup).

Genuine ‘breakthrough’, world-impact creativity is so rare, so difficult (far more difficult than commonly imagined) that it requires a special kind of mind – a mind especially designed for this kind of work (inner work). There need not be many such men – indeed, there should not be too many, since the necessary mind is relatively unfit for the primary, day-to-day, activities of survival and reproduction of the species. But such men are needed – sooner or later, from time to time.
These are the people who (whether we know their names or not) will almost-certainly be behind the scientific and technical breakthroughs that are the motor of civilization, these are people whose can inspire and unite society moving it towards greater things or out of the depths of despair and *ennui*; these are the people who can rescue a society on the brink of catastrophe.

The Endogenous personality is recognized because when this kind of creative personality is combined with high ‘general intelligence’, we get a potential genius – of greatness in proportion to their ability.

So, an Inner, Intuitive personality plus high Intelligence (or another special ability) is the Creative Triad and equals the Endogenous personality, or potential genius. The high intelligence serves as a kind of guarantee that the Endogenous personality is _positively adapted_ by his lop-sided focus, and inclination to be a creative specialist problem-solver in society; and is not merely a broken, sick or damaged individual who simply _cannot_ participate in normal society – perhaps through mental or physical illness.

The Endogenous personality will stay focused on a problem longer than most men – and he will look at the problem in a different way. He will deploy different (more inward) procedures of understanding – more detached, more abstracting. Hence he is more likely to see something new and useful in a new and different way.

His stance is less personal. He stands back to a greater extent than most. He sees the problem in a wider scope precisely because he sees the problem detached from normal personal concerns, such as status, sex, or wealth; none of which he really seems to care much about. For him, solving his problem is not a means to an end – a way of gaining status, wealth or sex – it is an end in itself. The inner man gets the greatest satisfaction from inner work – it is what he most wants to do.

In this short book, we will explore the Genius; the Endogenous type of personality including its exceptionally high intelligence. We will argue that the highly able Endogenous personality is indeed the archetypal genius; the engine, in particular, of the original innovations that are vital to civilization itself. Without genius, civilization will certainly continue to decline (and we will show that it is declining), and eventually collapse. With more geniuses, taken notice of, the process would be slowed and – who knows? – perhaps some genius could discover a way out?
We will demonstrate, in more depth, the importance to any society of nurturing a small number of such personalities; and, worryingly, we will find that they are less likely to manifest themselves now than was the case just a few generations ago.

We will argue, indeed, that we have a Genius Famine. Genius has now all-but disappeared from public view; partly because intelligence (which is strongly genetic) is in decline in the West, partly because social institutions no longer recognize or nurture genius, and partly because the modern West is actively hostile to genius.

Finally, we will look at what – if anything – can be done to rescue the genius and thus preserve civilization.
However, in order to understand the Endogenous Personality, we need to understand the nature of personality itself, as well as the nature of intelligence, as these two traits are at the heart of the Endogenous personality and of Genius.
