# What is Personality, What is Intelligence?

Intelligence and Personality are the two main ways that psychologists have developed for describing differences between people.

In brief – Intelligence is an ability, while personality is character; intelligence is general – with the level of intelligence affecting many specific abilities, while personality can be understood as a pattern of motivations, preferences, satisfactions.

In terms of computers – intelligence is something like the processing speed, while personality is about the types of software installed. Or, intelligence is about the efficiency of the brain, while personality is about what that brain is designed to do. Or intelligence is about how well the brain works; while personality describes the circuitry, the hard-wiring – what _kind_ of brain it is.

A further difference is that intelligence is measured by tests – IQ tests; while personality is evaluated by human beings – either self-rated using self-describing scales, or else rated by other people.

But a similarity is that both IQ and personality are (nearly always) comparative measurements. A person high in intelligence, or high on a personality trait such as Conscientiousness, is ‘high’ _relative to other people_. ‘High’ or ‘Low’, in both intelligence and personality, therefore does _not_ describe an objective measurement of a personal attribute in the way that (for example) high or low blood pressure or blood sugar measurements would.

## Personality

Personality is, in essence, our general way of being. Differences in personality predict differences in how people will respond in a certain situation.

Personality evaluations are usually measured by questionnaires: How close to you does a car moving at a certain speed have to be before you judge that it is too dangerous to cross the road in front of it? How many annoying things have to happen to you in a day before you lose your temper and raise your voice? How strongly do the emotions of others impact how you feel?

Different people will give different answers to these questions, in part because of variation in their personality. Typically, people are asked whether a certain behaviour, or like or dislike, is present or absent in them; or else asked to rate its strength. Multiple such questions can be analysed and averaged to yield a few personality ‘traits’ which cluster together.

The exact number of these traits used by psychologists depends on the purpose of the personality evaluation. The number can be as few as one general master trait (e.g. pro-social _versus_ asocial – see below), or dozens of specific traits such as aggression, or courage – but usually, for convenience, the number of traits used for describing personality have been something between about two and five.
Although we will be suggesting revisions and improvements to the scheme, many psychologists currently suggest that personality can best be understood in terms of five essential personality characteristics: these are the ‘Big 5’, which each make a scale between extremes separated by a dash:

(1) *Extraversion--Introversion*. Extraversion is a need for external stimulation – especially social stimulation; introversion is sufficient internal stimulation therefore independence from external stimuli.
(2) *Neuroticism--Emotional Stability*. Neuroticism relates to emotional instability – especially negative mood swings such as anxiety, depression, shyness.
(3) *Conscientiousness--Impulsiveness*: Conscientiousness refers to responsivity to social norms, usually leading to organized and self-disciplined behaviour.
(4) *Agreeableness (which is essentially the same as the Empathizing trait)--Indifference to other people*: Agreeableness shows itself in a high interest in other people, what they are thinking and how they feel.
(5) *Openness-Intellect--Aversion to change/ intellectual conservatism*: Openness references intellectual curiosity and a preference for novelty, creativity (in some sense of the word), hypnotisability, unusual psychological experiences. Openness weakly but significantly correlates with intelligence, as it is measuring some of the same things.

These five personality traits are (except for Openness--Intellect) regarded as independent of IQ scores (at least within normal IQ ranges); and our placing on them predicts how we behave.

For example, high Conscientiousness as a child predicts greater success in education and employment; high Neuroticism predicts problems with mood swings, anxiety and depression. High Openness-Intellect will tend to result in being a novelty-loving, impractical, perhaps artistic, academic or spiritual dreamer. A moderately high score, however, is a predictor of artistic success – or at least, on some measures of artistic success that focus on the production of novelty (although, we will argue, High Openness does not predict the genius type of creativity).[@2]

The Big Five were developed from the Big Three traits defined by psychologist Hans J. Eysenck (1916-1997), who arrived in England from Germany in the 1930s and became the most dominant personality in British academic psychology. The Big Three are Extraversion, Neuroticism and Psychoticism.[3] In effect, the Big Five dimensions of Conscientiousness and Agree-ableness are the opposites of various aspects of Eysenck’s Psychoticism; and Openness takes some aspects of Psychoticism and blends them with behaviours characteristic of modern intellectuals (as may be inferred from this description, we regard the Openness trait as a concept of dubious biological validity).

Like Eysenck, the British-born Canadian psychologist J. Philippe Rushton (1943-2012) was an original thinker, unafraid to tackle controversial ideas.[4] Rushton showed that the Big Five (and Big Three) are all co-correlated, and could all therefore be collapsed into a single personality variable, which he called the General Factor Personality (GFP).[5] GFP can be conceptualized as the single dimension of personality – from pro-social to a-social – which underlies the more specific person-ality traits – analogously to how general intelligence or ‘g’ underlies all the specific cognitive abilities, something which we explore below
So General Factor of Personality can be conceptualized as the degree to which a personality is _prosocial_– in other words, the degree to which someone has the kind of personality type and behaviours that underpin many socially desirable traits, the degree to which someone approximates to the type of person that makes for friendliness, helpfulness, being a ‘good neighbour’; for peaceful, orderly, cooperative, hard-working, placid citizens.

GFP describes a basic personality dimension, high levels of which (it is suggested) evolved as an adaptation in complex and stable societies so that people would ‘get along together’. So a person with high GFP would be sociably extraverted, be empathic and concerned with the feelings of others, conscientious and self-disciplined in pursuit of socially-approved goals, have stable emotions, and be open to new ideas.

Marvellous as the high GFP person sounds, throughout this book we argue that a personality of almost the opposite type is necessary for the true genius (not the only thing required, but necessary) – we call this the Endogenous personality, and this new concept will soon be described in detail.

But in summary, the Endogenous personality, necessary for genius, is self-sufficient, indifferent to the opinions of others or normal social aims, being instead wrapped-up in his own personal goals, and making judgements using his own internal, subjective evaluation systems – he will work very hard and for long periods on his own projects, but will not willingly go-along with other people’s plans and schemes. But more on this later…

Personality traits, depending on how they are measured, have been shown to be in the region of 50% to around 70% heritable, based mainly on twin and adoption studies.[6] (Heritability is a measure of how closely parents resemble their children in a group study – the number refers to how closely the parents’ personalities predict the child’s – heritability of one would mean that children’s personalities were wholly a product of their parents’ personalities; zero would mean the mathematical relationship between parent and offspring’s personalities was random.)

Since the heritability of personality is less than one, some combination of chance and the environment does affect the kind of personality which you develop, but only within certain genetic limits. An unstable, dangerous childhood will tend to increase mental instability, and those who experience it will learn to see the world as a dangerous place – and this may have a lasting effect on their behaviour (this calibration of adult behaviour to childhood environment is the subject of Life History studies in biology – humans as well as animals).[7]

For instance, when childhood is unpredictable and dangerous, children will tend to be calibrated to ‘live for the now,’ so displaying lower Conscientiousness, and they may be suspicious of other people, leading to lower Agreeableness.

Another example is that girls who have grown up in sexually-unstable situations seem to adopt a short-termist sexual strategy, having children with a variety of men who are chosen for their dominance (hence probably good genes) rather than their ability to remain committed to a relationship and provide resources over the long term. In slang terms, girls from unstable homes may exhibit a preference for ‘cads’ rather than ‘Dads’.[8]

## Intelligence

_So much for personality, what then is intelligence?_

‘Intelligence’ can be seen as the ability to think abstractly and to learn quickly – this leads to an ability to solve problems quickly, but only when those problems have previously been encountered. In problem solving, intelligence provides fast processing and a larger knowledge base, but intelligence is _not_ about being original or creative.

Intelligence is measured by IQ tests (meaning Intelligence Quotient; see below) and IQ test scores in childhood will predict many important things – higher intelligence predicts higher education level, higher socio-economic status, higher salary, better health, greater civic participation,[9] lower impulsivity, and longer lifespan[10]; lower intelligence predicts higher criminality, and (probably causally related to crime) shorter-term future-orientation.[11]

In general, therefore, high intelligence predicts desirable outcomes – however there is one important exception: high intelligence, in modern societies, predicts lower fertility – especially among women. Thus, in modern societies (with access to birth control) the most intelligent women average less than one child, because so many intelligent women have zero children, and very few have large families.[12]

Some people argue for a broader or multiple definition of intelligence, including ‘emotional intelligence’ for example. But there is, in general, no need to separate this from ‘intelligence’ as we define it. The ability to solve social problems has been shown to be predicted by intelligence; and all cognitive aptitudes always co-correlate in rigorous group studies, even though individuals (including geniuses) may show significantly divergent specific cognitive strengths and weaknesses.[13]

Intelligence is measured by IQ tests. These typically measure three forms of intelligence: verbal, numerical (mathematical) and spatial (geometric). Some individual people are higher in one form of intelligence than another, and rarely they may have above average measures in one measure of intelligence and below average in another – but, overall, in group studies all of the many different measures of cognitive ability (vocabulary, general knowledge, reading ability, puzzle solving, algebra, what-comes-next sequences of numbers or of symbols etc.) will always positively correlate. It is consistently found that, within-groups and between-groups, high ability in one task goes with high ability in other tasks, and _vice versa_.

This is why intelligence is called ‘general’, and why it can be compared with processing speed in a computer – a ‘faster’ processing computer is better at doing almost every kind of task – _all_ the types of software (graphics, statistics, word processing etc.) will run more efficiently. And not only does a fast computer complete tasks more quickly, but a fast computer can also do things that are – in practice – impossible for a slower computer (which will be unable to cope with the load and sequence of computations, and will ‘seize-up’.).

The positive correlation between cognitive measures means that we can talk about a ‘general factor’ that underpins all of them. The IQ is a statistical construct which measures an inferred ability which underlies all of these cognitive abilities. This underlying ability is known as ‘g’ for ‘general intelligence.’

Intelligence increases throughout childhood and decreases from middle age onwards (probably from early adulthood, but slowly) and, as such, IQ is usually a comparative measure – comparing the individual with a group sample of the same age. The IQ number is a way of expressing the individual’s position in a rank ordering of IQ test scores for his age group; hence the term ‘intelligence quotient’ (IQ) (the average IQ is called 100, often calibrated against the UK population average), larger numbers are above average intelligence and lower numbers are below average (expressing this in percentage terms based on a normal distribution curve with a standard deviation of (usually) 15 IQ points – for instance an IQ above 120 is approximately in the top ten per cent of the population; and 130 in the top two per cent).

It is very important to recognise that IQ is therefore a comparative measure – and this limits its usefulness – because intelligence in a person or group is being measured only _relative_ to another person or group.

The results of IQ tests strongly correlate with intuitive measures of thinking ability (such as school work) and they are not merely culturally influenced (although, naturally, culture and familiarity do have some influence). We know that IQ testing is valid and robust across cultures, because the cultures (or sub-cultures) that do badly in IQ tests do the least-badly on the most culturally-biased parts of the test, and also because the IQ test results correlate positively with something objective – that is, with differences in simple reaction times.[14] The correlation between intelligence and reaction times means that intelligence is a good indicator of how well the nervous system is running.
As already noted, intelligence is a vital predictor of life outcomes. Approximately 70% of the variance in school performance is explained by differences in intelligence, 50% of the variance among university undergraduate performance and 40% of the variance in postgraduate performance. Intelligence explains about 30% of the variance in salary and is a clear predictor of job status.[15]

It has been found that less-selective professionals, like teachers and nurses, have an IQ of about 110, while it is 120 for doctors and lawyers, and even higher for those who rise to the top of these professions.[16] Within academia, the average PhD student in education has an IQ of around 117, while the average PhD student in Physics has an IQ of 130.[17]

As with personality, intelligence is strongly heritable – indeed the heritability measures are higher for intelligence than personality, perhaps because IQ is a more precise and valid measure than are personality ratings. Around 80% of the variance in intelligence is probably genetic – over-whelmingly, therefore, intelligence is inherited from parents.[18]

Environmental factors include sufficient nutrition and a sufficiently intellectually stimulating environment when growing up. Just as important is an intellectually stimulating adult environment, which those with high intelligence will tend to create for themselves. For this reason, among others, the genetic component of IQ during childhood is relatively low, as the child’s environment will reflect its parents’ intelligence. Only as the child reaches adulthood will its environment reflect its own intelligence, leading to a genetic component of 80%.[19]
High intelligence is a sign of having an overall-efficient, fast-processing brain – requiring (as American psychologist Geoffrey Miller has pointed-out) ‘good genes’; which mostly means a minimal load of deleterious mutations.[20]

Deleterious genetic mutations occur spontaneously in every generation – due to any cause of mutation (radiation, chemical, heat etc.) or from DNA copying errors – and some non-lethal but potentially-damaging mutated genes are usually inherited from parents. Nearly all chance gene mutations are harmful – and only very rarely are they ‘adaptive’ and improving of function (but it is these very rare beneficial mutations that are the basis of evolution by natural selection).[21]

In general, however, spontaneous mutations reduce ‘fitness’ (i.e. reduce reproductive potential, by damaging heritable genetic quality) and the human species has needed to prevent mutations from accumulating every generation as inherited mutations are added-to by new mutations. Somehow, these mutations need to be continually removed from the human population, or else they would overwhelm and destroy the species in a process termed Mutational Meltdown. Thus, following Miller, we would expect the more intelligent to have bodies – and especially nervous systems – that function particularly well and especially in certain specific respects. For example, a high functioning nervous system has been shown to be associated with a more efficient and stronger immune response.[22]

## The difference between intelligence and IQ

The difference between intelligence and IQ is that intelligence is the real, underlying psychological function, whereas IQ is a score achieved in a test – a score which is intended to compare and measure intelligence but which is an indirect, only partly-precise and only partly-valid measure of intelligence. The IQ test is clearly a sound measure of intelligence – because IQ scores correlate with other measures of cognitive problem solving ability and thus brain functioning – but it is imperfect, meaning other factors than intelligence can impact the score. In much the same way, a bathroom scales measures weight – its results correlate with other measures of weight – but some scales are better than others and no scales is perfect.

Therefore, we can think of a qualitative, subjective understanding of the phenomenon of real intelligence as an _irreducible entity_ – not understood in terms of other things nor only in terms of what it _does_, but in terms of itself as _a real thing_ which we can detect and measure only indirectly. And we can then conceptualize IQ as the practical, simplified, publicly-shareable way of conceptualizing and investigating intelligence.

IQ can be, and usually is, researched in a ‘theory-free’ fashion, with operational definitions based on proxy description, measurement by comparison, and correlation – indeed intelligence is sometimes asserted to be nothing-more than a mathematical-derivation from IQ scores.

But we would emphasize that to understand intelligence requires understanding that sometimes a person may be of high intelligence and _not_ have a similarly high IQ score (in other words, their IQ score is under-estimating their intelligence) – and that this may be the case no matter how validly, how often and how carefully the IQ is measured and calculated. And another person _may_ have high IQ scores, measured in the best ways and by the best methods, yet _not_ be of similarly high intelligence (in other words, their IQ score is _over_-estimating their intelligence).

Highly intelligent people who do _not_ score as highly on IQ tests are easy to understand – because anything which reduces test performance could lead to this outcome: illness, pain, impaired consciousness and impaired concentration from sleepiness, drugs, drug-withdrawal, mental illness ... there are multiple causes, and some are chronic (long-lasting, perhaps life-long).

And people with high IQ scores who are _not_ of similarly high intelligence to their scores are familiar to anyone who has attended a highly-selective college or educational programme or who are members of intellectually ‘elite’ professions; since they typically make-up a large proportion of participants. The ‘Flynn Effect,’ named after its discoverer New Zealand psychologist James Flynn, refers to the phenomenon of rising average IQ scores over the twentieth century in Western countries. The fact that this has taken place in a context of declining average real-intelligence means that the Flynn Effect can indeed be understood as evidence that IQ tests measure issues other than just intelligence, meaning they are imperfect. (Plus, even the most reliable IQ test only has a reliability of about 0.9 when retesting the same person.)

One possible explanation for the Flynn Effect, proposed by Flynn himself, is that modern society – due to higher levels of education in the general population – makes us think in a more scientific way and this ability is partially a reflection of intelligence and partially of a separate ability that does not rely on intelligence.[23] As such, IQ tests can be used to compare intelligence within a current population but they cannot be used as easily to make comparisons over time because they are examinations and people will tend to get better at them by practicing them and thinking in the way that permits optimum performance in them as society becomes more educated. So, up to a point, IQ scores may increase over time, despite the fact that intelligence is decreasing.

After (probably) six or eight generations of rising average IQ scores and falling real-general intelligence; there has been a progressive breakdown in the strength of correlation between intelligence measured in terms of IQ scores, and intelligence understood as a real underlying, brain functional phenomenon. Indeed, it seems likely that many or most people among modern high IQ scorers do _not_ have similarly high real-intelligence. This would be expected to apply especially at highly-educationally-selective institutions where Endogenous personalities are substantially selected-out by the decades-long trend for an increasingly-high minimum-threshold of conscientiousness imposed by educational qualifications.

The correlation between IQ score and ‘g’ was probably much higher in the past (a century plus ago) than it is now – meaning that the distinction between IQ score and real, underlying intelligence is more important now than it used to be.

## The evolution of higher intelligence

Geoffrey Miller’s emphasis on intelligence (he emphasizes particularly ‘creative’ intelligence) providing a ‘fitness measure’ which one person can evaluate in another; and his noting that relative IQ provides a quantitative correlate of deleterious mutations – is worth pausing over and amplifying.

This implies that high IQ serves as a kind-of guarantee and advertisement of ‘good genes’ – and this is why high intelligence is regarded as attractive, and therefore why men and women of higher intelligence tend to pair-up in marriage in much the same way that good-looking men and women tend to pair-up (this system of like pairing with like is termed ‘assortative mating’).

We have already noted that intelligence correlates with fast reaction times. This strongly implies that ‘intelligence’ is simply the function of a brain that is working well, just as strength is the function of muscle that is working well. The human body has evolved to work optimally well in a particular environment and the same is true of the human brain. Detailed historical research by British economist Gregory Clark has shown that until the Industrial Revolution a form of natural selection was operating in Western societies. Those who were not physically strong, who did not have strong immune systems, who were of low intelligence and unable to work steadily for long hours would usually either die as children or be unable to raise children of their own; and would thus be unable to pass on their deleterious genes.[24]

In other words, until about 1800 only the minority of people with (on average) the ‘best genes’ (i.e. the lowest mutation load) would be able to survive and reproduce; and among the great majority of the population only a very small proportion of their offspring (averaging much less than two, probably less than one, per woman) would survive to a healthy adulthood, reproduce and raise children of their own. In this context, which was for almost all of human history until about two hundred years ago; both new and inherited deleterious mutations were filtered-out, or _purged_, from the population every generation by this very harsh form of natural selection.

In much the same way, the number of surviving offspring was predicted by socioeconomic status – and especially by intelligence – in pre-Industrial Europe. Clark shows that in seventeenth century England, for example, the richer 50% of those who left wills had 40% higher completed fertility (children of their own, still alive when they passed away) than did the poorer 50%. In essence, the English intellectual middle classes (e.g. senior clerks, merchants, lawyers, churchmen, physicians etc.) and upper class seem to have been the most successful at reproducing for several hundred years – providing the majority of viable children with each generation so that over many generations their descendants (inheriting their ancestors’ high intelligence) expanded as a proportion to become almost all of the English population.

Those with the lowest levels of deleterious mutations would, _for that reason_, have high intelligence and a high functioning immune system. As such, they would attain or maintain high socioeconomic status, and, in a context of limited medicine, their offspring would be more likely to survive. In addition, genes for intelligence would permit them to become wealthier, meaning they could better protect themselves, and their offspring, from disease, poor living conditions and accidents; and they could afford to have large numbers of children (ensuring at least some survived), without risking starvation. These two related processes would ensure that the children of the richer survived better.

The message seems to be that in pre-industrial Europe (before about 1800-1850) natural selection on humans operated mostly via mortality rates – especially child mortality rates. An average of more than half of children would die before adulthood, but this consisted of near total mortality rates among the children of the poor, and ill, and of low intelligence or ‘feckless’ personality; whereas among the skilled middle classes (clerks, merchants, lawyers, doctors etc.) the mortality rates were lower and fertility (number of births) was high. Therefore in each generation most of the children came from the most intelligent group in the population, and over several generations almost all the population would have been children whose ancestors were the most intelligent (also conscientious, and relatively peaceful) sector of the population.

(This is why anyone English who has ever traced their family tree will find that by the sixteenth century – when records begin – their ancestors are, at the very least, wealthy though non-aristocratic farmers (‘yeomen’ or richer ‘husbandmen’).[25] And this is why every English person alive is descended from King Edward III – 1312-1377.).[26]

Clark argues that this harsh natural selection resulted in an increase of average intelligence with every generation, and ultimately culminated in the intellectual and social breakthroughs of the Industrial Revolution. It meant that there was a large percentage of the society whose intelligence was so high that the necessary breakthroughs could be made, and that the society as a whole was sufficiently intelligent such that it could maintain and even develop these breakthroughs. Furthermore, the workforce developed a personality type which was pre-adapted (by preceding Medieval natural selection, operating over several hundred years) to the needs of large scale industry and complex social organization.

## The ending of selection for higher intelligence

This ‘eugenic’ (i.e. genetic-quality, or ‘fitness’-increasing) environment rapidly stopped in the wake of the Industrial Revolution, and soon went into reverse; with socioeconomic status becoming _negatively_ associated with fertility, especially among women. In other words, after the Industrial Revolution the direction of natural selection turned upside-down, with higher social status, wealth and education leading to lower reproductive success.

This process – known as dysgenics (i.e. selection that is reducing ‘fitness’ – in the sense of heritable genetic quality, where deleterious mutat-ions are taken as an index of low heritable quality hence fitness) – has been documented by British psychologist Richard Lynn. In addition, Lynn notes that the pattern of reproduction ceased to eliminate genes that would lead to a poor immune system or various physical impairments. Modern medicine means that genetically-damaged people can procreate leading to a dysgenic impact on health, more deleterious genes and thus a further negative impact on intelligence.[27]

Probably the most significant impact of the Industrial Revolution was in reducing child mortality rates from more than half to (eventually) just about one per cent. For the first time in history, almost all the population, including the poorest classes and those with the heaviest mutation loads, were leaving behind more than two surviving children. Over a few generations, the mutational load must have accumulated – fitness must have declined – and average intelligence must have reduced due to the effects of deleterious mutations on brain development and functioning.

Since intelligence is correlated with genetic quality, this inferred population level mutation accumulation implies that average intelligence should have declined since the Industrial Revolution.

The inferred decline in general intelligence due to both mutation accumulation plus ‘dysgenic’ patterns of fertility, can be measured using simple reaction times, which correlate with ‘g’ – and it has been found that reaction times have slowed considerably since the late 1800s when reaction times measurements were first performed.

We will return to discuss this matter further – but so far it seems that intelligence first increased due to natural selection in the Medieval era; then has declined due to the changes in natural selection at the time of the Industrial Revolution.

So, what about personality – how was personality affected by natural selection on the European population, first in the Medieval era, then through the Industrial Revolution?

In sum, it seems that Medieval Europe was a breeding ground for high intelligence – which is one component of genius; but also a breeding ground for pro-social extraverted people of stable ‘high GFP’ personality type, high in conscientiousness, empathic; obedient, good at working regular hours and getting along with their neighbours.

However, although high intelligence is a component of genius, and although an average pro-social personality type is useful, and perhaps essential, for successful industrial societies; the high GFP/ pro-social personality is almost the _opposite_ of that required to make a genius. And yet, late Medieval and Renaissance Europe was a veritable hotbed of genius, and it was these geniuses who enabled and triggered the Industrial Revolution.

So, how can the average population increase in pro-social personality, yet that same population generate individuals of exceptionally high intelligence who have the ‘asocial’ Endogenous personality type, some of whom made major breakthroughs and became recognized as geniuses?

## Two ways of being highly intelligent; Good genes or the Endogenous personality

Most people would probably say that an Endogenous personality was a matter of sheer chance – that in a population characterized by high GFP, a few individuals just happened (by random variation) to have low GFP – and this low GFP/ Endogenous personality group included some individuals of very high intelligence who were the potential geniuses.

But our suggestion is different: picking-up on a suggestion from British psychologist Michael A. Woodley, we suggest that the high rate of European genius was not an accident. We will argue that the Medieval European population was under group selection as well as individual natural selection – and specifically that it was group selection which led to the evolution of geniuses.

In a nutshell, the Endogenous personality evolved in a high intelligence population to provide a significant minority of geniuses, whose function was to be specialists in creative problem solving and invention. The activities of this minority of geniuses had disproportionate impact, and were of general benefit to the survival and /or expansion of the social group among whom the geniuses lived and worked.

Indeed, we would argue that there are two ways of being exceptionally intelligent. The usual way is that someone in a population is exceptionally intelligent is by what is termed Good Genes: that is, having few genetic faults or errors – the person has a structurally normal brain, but with nothing (or nothing much) wrong with it. In other words he has a low load of deleterious mutations (or, conversely, he is _not_ suffering from mutation accumulation).

But there is another way – which is by having an Endogenous personality – which means that his brain is purposely _designed_ (by group selection – the mechanisms of which are currently poorly understood) to be creative, to make breakthroughs. Such a person is, in sum, a genius (albeit very probably _not_ a world historical genius; but a tribal or local genius).

Our assumption is that in the potential genius – and if we could measure it, which is not possible at present – we would see a brain _wired-up to be intelligent_ and not merely intelligent, but also wired-up to be more orientated towards internal processing – more intuitively creative, more internally-motivated.

Therefore the brain of an Endogenous personality is an _evolutionarily specialized brain_; which has high intelligence not so much negatively from lack of mutations; as positively – because it is a brain ‘designed’ (by natural selection) to be highly efficient for the purpose of creative discovery.

And this is why the genius has a special (Endogenous) personality. Usually personality and intelligence are almost distinct and little-correlated; but the brain of a genius is differently wired from a normal brain: it is a specialized and purposive brain, a lop-sided brain, a brain in which some circuits usually used for social intelligence and reproductive success are co-opted to serving a creative purpose.

In sum, _the brain of a genius is one that is specialized for creative discovery_ and both high intelligence and an ‘inner-oriented’ personality are features of this specialization. This is why personality and intelligence go together in the genius, whereas in ‘normal people’ personality and genius can vary almost independently and there is little correlation between the two.

We have discussed, then, the concepts of personality and intelligence and the factors that lead to differences in them. We will now attempt to understand how these relate to genius.
