# Different understandings of Genius

What is the nature of ‘genius’? There are many layers to genius – although typically only those nearest the surface are considered. Some of the main layers are:

1. Sociological: Impact on history
2. Biological–differential: Reproductive Success
3. Biological–ideal: Fitness
4. Philosophical–Theological: Fitness for what? Ultimate Purpose?

Let us consider each in turn.

### 1. Sociological {-}

This is the usual level of analysis, the usual definition of a genius. A genius is seen as a person who has made a disproportionately large impact on human history. This can be measured more-or-less objectively by evaluating the consensus of expert historians of science, technology, arts, literature etc. – since these experts exhibit a high level of agreement concerning what is most important.
While this is, broadly, the interpretation we use in this book with which to frame genius – the sociological category is over inclusive, since individuals may have a large impact on human history despite a non-exceptional, non-genius personality or mediocre ability; as examples due to accident of birth (e.g. some monarchs), accidents of public response (the ‘famous for being famous’ phenomenon), being married to a major figure and thereby having power and influence bestowed for that reason; or simply from the luck, or misfortune, of being in the right place at the right time.

### 2. Biological – Differential {-}

A genius is seen in biological terms as one who makes a disproportionately large impact on human reproduction. This is measured in terms of reproductive success, which is measured in terms of the number of descendants of a genius and/or the group to which he belongs to – or, in the relevant case of group selection, biological success is measured in terms of the survival and expansion of the social group to which the genius belongs.
By this measure, a genius is one who causes a measurable increase in the numbers or proportion of his society (by some measure) – examples of such geniuses would be those who created the technical breakthroughs leading to the Agrarian and Industrial Revolutions – for example Robert Bakewell (1725-95) the animal breeder, Coke of Norfolk (Thomas Coke, Earl of Leicester, 1754-1842) the deviser of more efficient farming methods; or Richard Trevithick (1771-1833) the inventor of the high pressure steam engine.
And an ‘anti-genius’ would be one who did the opposite: caused a decline in the number or proportion of descendants or group members. Candidates would include Napoleon, whose policies and wars seem to have caused a collapse in the French population relative to the British one.[28]

### 3. Biological – Ideal {-}

This takes account of the objective, not differential, effect of ‘fitness’ (here defined in terms of heritable genetic quality) by estimating organismal functionality – the reproductive potential of an average organism is a given environment.
For example, a lineage may increase in its numbers or proportion of the population; even though there is an accumulation of deleterious mutations which damage basic functionality. We would argue that this was happening in Europe among the lower classes during the 19th century. One effect of the Industrial Revolution, in Gregory Clark’s work, was that the lower classes increased both numerically and as a proportion of the European population (due to maintaining high fertility as child mortality rates declined) – however, we argue that despite this ‘success’ the underlying fitness/genetic quality of the lower classes was actually declining, due to mutation accumulation.

So reproductive success (absolute or relative) can increase even as the underlying functionality or fitness declines. This can happen when the environment is less harsh, inflicts a lower mortality rate – as with animals in a zoo, or humans in modern society. This would be seen if the experiment was done of returning an animal, or human, to its ‘wild’ or original environment – when the capacity of the organism (or species) to survive and reproduce will be seen to have declined.

We assume that this has happened to modern Man in general and everywhere since the Industrial Revolution: i.e. his ‘ideal’ fitness has declined; and this would be seen if or when modern Man had to return to pre-1800 conditions, for example if the Industrial Revolution unravelled and the world returned to a Medieval type agrarian society.

If or when this happens, we would predict that the human population would collapse to numbers significantly _below_ 1800 levels, and would stay low for several or many generations – simply because Men would be less fit, less well adapted (their adaptations having been destroyed by mutation accumulation). But this fitness decline is presently obscured by the ‘softness’ and abundance of modern life, which is itself a product of breakthroughs by geniuses of the past.

Thus there is a lag between the onset of mutation accumulation and the effects working their way through the population. And the inertial benefit of past geniuses continues to produce a comfortable and low-mortality environment Man for some generations after genius has itself dwindled.

### 4. Philosophical – Theological – Fitness for what? {-}

If an ideal, not actual, concept of fitness is to be used, then it is not clear what the environment against which fitness or functionality should be measured is. This creates a need for, opens space for, a philosophical discourse about what Man’s fitness _ought_ to be.

By this account, a genius is one who enhances his group’s fitness for (or functionality-in) the kind of environment which Man is _aiming-for_, or wants to have. One version of this would be a genius tending to create Men fitted for utopia. Such a definition would include philosophers in the broad sense of the word; artists, painters, poets, literary authors etc. – from Plato to Hegel and beyond.

In ultimate terms, the deepest understanding of genius is perhaps one who promotes the ultimate purpose of Life-itself, in terms of the divine plan or ultimate purpose of life. This definition would include religious founders, prophets, saints, holy men and women; and also some artists, poets, and thinkers.

Overall, it can be seen that these four definitions of genius dissociate. For example, a genius who promotes theological ultimate purpose may damage reproductive success (if a good new religious group is exterminated). A genius who promotes reproductive success may damage ideal fitness (i.e. the population increases but so does the deleterious mutation load).

In this book, we will understand ‘genius’ primarily in the sociological sense: that is, a world-historical genius is seen as a person who has made a disproportionately large impact on human history – but we will restrict the definition of genius to a specific psychological group within this category: thus, our concept of a genius is one who has the Endogenous personality and who, _because of this_, has made a disproportionate impact on human society and history.

Furthermore, we consider the _potential_ genius to be someone who has the Endogenous personality but has not, or not yet, made a large impact; and geniuses may also be classified by the scale and depth of their impact – some with an impact that is international and permanent, some with a local and more temporary impact.

And, of course, the personal identity of a genius may or may not be known; or may be lost to history – so we know the identity of Shakespeare who wrote the Sonnets; but the names of those geniuses who wrote the Border Ballads (coming from the Border of England and Scotland in the late Medieval era, and later recorded from oral tradition by the likes of the great novelist and poet Sir Walter Scott – 1771-1832) are all lost, and perhaps never were known.[29]

This, of course, means that, from a particular vantage point, it is possible to distinguish between the impact of a ‘good’ genius and an ‘evil’ genius’ according to the nature of the socio-historical impact; and we will also consider the semi-genius or borderline genius – someone who has made a significant impact short of crossing the threshold into world historical importance.
