# The Creative Triad


The Endogenous personality, as we have discussed, refers to someone who is inner-orientated. Our suggestion is that this personality complex is associated with genuine creativity and – in rare instances, with creative genius. This raises an important question immediately. What does it mean to be creative? What is the nature of creativity?

We can conceive of a Creative Triad. It is composed of (1) Innate ability (2) Inner-motivation, and (3) Intuitive thinking. This triad is the essence of how we use the word ‘creative’ in everyday life. The ‘creative’ type is the ‘arty’ type: the novelist, the poet, and especially the artist; and by extension, also the truly original scientist and technological innovator.

Genius is made possible when all parts of this Triad flow together in a particular way: a person is internally-motivated to pursue that for which he has a natural ability; and does so in an ‘‘intuitive’’ way that mobilizes his deepest self, all his mental powers. Major genius occurs when the ‘natural ability’ dimension is also extremely high.

But people can still be ‘creative’ yet not reach the level of genius, they may be considered as semi- or borderline-genius when their historic impact on a society is real but modest. For example, there are numerous ‘local geniuses’ who are relative geniuses compared to those around them, and make genius type social contributions – but their impact is geographically or temporally restricted. Most geniuses are, in fact, of this type.

And, of course, a potential genius may (for reasons we will discuss later) fail to make an influential break-through or may make a breakthrough that fails to be recognized and acted-upon.

Before turning, then, to the nature of ‘the creative’ we need to be clear on the nature of each of its component parts and how they contribute to creativity and genius. It is clear how ‘innate ability’ does, but what about intuition? What is intuition?

We could approach intuition by stating that intuition is the mode of thought of the private soul/ the real self/ inner consciousness – that is to say the most profound, the most secret, fundamental mode of thought. Intuition can be contrasted with two (lower, subordinated) modes of thinking: passions versus reason; the body v the brain; gut-feelings v head-knowledge; instinct v logic. These two modes are not absolutely distinct, but we think they can usefully be distinguished.

So, what is the thought mode of intuition? It is not by instinct nor by logic – but by something of both, and more. Therefore, intuition is a mode of thinking which simultaneously uses emotion and logic but operating in a context of (for example) motivation, purpose, meaning and relationships. In a nutshell, _intuition uses all possible modes of thinking_; and this is why intuition leads to a greater feeling of sureness, of certainty, than do other, more partial forms of thought.

The result of intuition is therefore an evaluation which is uniquely convincing because it is validated by the full range of positive responses. It is an insight that satisfies both logic and reason, and also ‘feels’ right. By contrast, if we use only (for example) logic, or only emotions, to evaluate something; then the evaluation will be incomplete, and evaluation in one sub-mode may be contradicted by evaluation in another sub-mode – as when logic and emotions reach different conclusions, point in different directions, contradict one-another – and we feel confused or torn because our head and our heart are in conflict.

Only the evaluations of intuition are fully satisfying, fully convincing, and harmonious. Only the evaluations of intuition mobilize the whole range of thought modes. Thus _intuition is the most powerful mode of thought_, and the only mode of thought capable of mobilizing the fullest degree of motivation. Intuition is what makes us care most about ideas: it is what _engages_ us with creativity. This is why intuition is necessary to the highest levels of creativity, to the greatest attainments of genius.
Our second question is: what is inner motivation and why is it necessary for creativity and genius?

The genius must combine the inner orientation of the contemplative – in order to find his own problem, the problem he is destined to work on; with an inner motivation towards action directed to solving this problem. He must desire to translate understanding into engagement; not just to contemplate reality, but to ‘solve’ reality.

So, something deep within the genius – and not the promise of an external reward – makes him want to fully comprehend or improve or express the nature of reality. Because his motivation comes from within, and he is focused upon a problem which also comes from within, the genius is not easily discouraged; his drive will enable him – will indeed compel him – to keep pushing and pushing, even when support is withdrawn or he is met by discouragement and failure.

Therefore – when it comes to his own problem – the genius is autonomous, self-motivating, tenacious and stubborn in pursuit of his Destiny. He will see the Genius Quest, as we might term it, through to its conclusion in Illumination or ‘die in the attempt’ – unless he is actively prevented from doing so.

In summary, the creative personality of a genius involves an Inner orientation which includes a basis in intuitive modes of thinking and an inner source of motivation – we will now further explore the nature of this motivation.
