# What Motivates the Genius Quest?


The genius has a ‘journey’ to make, a ‘path’ to take – a ‘way’ to live: a Quest.

Pursuing this Quest is the Destiny of the genius – it is what he is ‘meant to do’.

After this, various things may happen. The Quest may be discovered and embarked upon, but there is no guarantee it will be completed. It may be tried but may fail. The genius may die, or get sick before it is finished – or in some way be thwarted or defeated. The Destiny may be accepted, but may later be abandoned; because the commitment must be renewed many times. Illumination may actually be achieved but rejected by society – the genius unrecognised. Or, Illumination may be achieved but stolen and no credit given. Or the Quest may be achieved, and the Illumination socially-accepted, and acknowledgement may even be given… but then the genius becomes corrupted into careerism, status seeking, pleasure seeking, or whatever takes him away from his Destiny.

As an example of an abandoned Quest, the mathematician and historian of science Jacob Bronowski (1908-1974) claimed, in in his 1972 TV series _The Ascent of Man_, that this was the fate of the mathematical and computing genius – and friend of Bronowski’s – John von Neumann (1903-1957). Von Neumann was, late in life, lured away from focusing on his intellectual pursuits by love of power, status and prestige – leaving his work incomplete. And such was the greatness of von Neumann, that it proved difficult, indeed impossible, for anyone else to complete it. So, here was a real genius who accepted and partially-completed his unique Quest – yet without quite finishing what he began.

## Psychoticism versus Openness

This emphasis on Destiny stresses that the genius has an unusual life, compared with normal people. But what does the genius get out of his unusual life?

Usually, he will simply enjoy being creative; and, indeed, being-creative will be a significant part of his sense of self, consequently he will be a noticeably different kind of person from the one whom we would see as ‘conventional.’

Hans Eysenck regarded creativity as an aspect of the Psychoticism trait – indicating a particular way of thinking and relating to the world which incorporated creativity as positive, and psychotic and psychopathic traits as negative, aspects of this trait.

Working more recently, British psychologist Daniel Nettle’s review of the psychological literature has shown that certain personality traits – in particular Openness-Intellect and Neuroticism – are associated with being creative, quite independent of being a highly successful creative – and indeed most personality psychologists nowadays regard Openness as the characteristic trait of a creative person.[@30]

So which is the best way of conceptualizing the personality of a creative person? Is it the eccentricity and originality and semi-craziness of Psychoticism, or the novelty-generation; and clever, fashionable fertility of Openness?

This is a topic to which we will return, but in brief we favour the older concept of Psychoticism as a better description of creativity – and we have derived the Endogenous personality from Eysenck’s analysis of the genius. However, we have departed from Eysenck by emphasizing that the high Endogenicity variable is rooted in group adaptiveness, and not in individual pathology. Also, we focus on a brain specialized by an innate _inner-ness of orientation_ as the basis of the personality trait cluster; whereas Eysenck explained higher Psychoticism in terms of a broader field of associations.

Our reason for our preference and emphasis for rejecting the currently dominant explanation of creativity by Openness and our advocacy of a development of the older idea of Psychoticism; is that Openness and Psychoticism (Endogenous personality) are at opposite ends of the General Factor Personality dimension: Openness is pro-social and Psychoticism/ Endogenous is a-social.

In other words, Openness type creativity is a response from a conscientious and empathic person to social demands or needs; while Psychoticism/ Endogenous creativity comes from the inner and innate drive of someone substantially indifferent to current societal self-awareness, knowledge and roles.

As such, we would suggest that ‘creative’ is not what you ‘do’ but what you ‘are.’

## The satisfactions of creativity

Creative people thus reflect a certain kind of personality, leading to characteristic behaviours. But why do creative people behave creatively? What exactly do ‘creatives’ get out of being creative? What, in other words, is the _phenomenology_ of creativity? (Note: Phenomenology refers to first-person, inner, subjective experience – how things look ‘from the inside’).

People could only be creative by disposition if creativity were supported with positive and rewarding emotions and/or provided relief from negative or aversive emotions. This would seem to work in three stages:

> Discontent – Delight – Satisfaction

Corresponding to:

> Perceiving a Problem – Having an Insight – Generating a Solution

Therefore, creativity is driven by a negative or ‘Dysphoric’ feeling – that some state of affairs produces an emotion of dissatisfaction. ‘The creative’ (as we shall term him) then turns his attention to this ‘‘problem’’ – and he enjoys working on the problem (that is, he enjoys ‘_being_ creative’); and finally he may come up with an insight which leads to a euphoric feeling of delight.

So, the creative is rewarded up-front for generating insights – by working on a problem he both gets relief from a negative state of inner dissatisfaction and is also positively rewarded by an inner fulfilment by the work – and this happens whether or not his insights eventually turn-out to be answers. As such, the creative will tend to generate insights _for the sheer fun of it!_ – and even if the insights turn-out to be trivial, erroneous, useless, or harmful.

But, finally, with persistence and luck on his side; let us say that the creative comes up with a solution to the problem: a solution which, for a shortish period (minutes or hours, perhaps), makes him feel joyously happy or ‘Euphoric’!

Thus a Dysphoric state of Discontent has then been replaced by a Euphoric state; and when Euphoria subsides the successful creative will move onto a longer-term and sustained state of satisfaction or gratification – and this can be termed ‘Euthymic’, meaning a state of ‘normal’ good mood. Therefore, first Euphoria, then Euthymia are the emotional rewards for creativity.
So, in terms of phenomenology, it goes:

> Dysphoria – Euphoria – Euthymia

Or, in English: Discontent, Bliss, Satisfaction

In terms of the larger picture of Life, this is the discontented state of seeking Destiny and the gratification of discovering it; embarking on a Quest – which is itself a satisfying albeit frustrating activity; and finally achieving Illumination – which leads to an acute state of bliss then a chronic state of satisfaction (and quite likely a new search for another Destiny).

Therefore, for the creative person, a normal life in conformity with social expectations is unsatisfying; but being creative is rewarding. Such a person will be _spontaneously_ creative, as a consequence of their inner drives and personal satisfactions; and creative whether asked to be creative or not, whether it is useful or not, and whether he is sufficiently knowledgeable and competent for the task or not.

Accordingly, if real creativity is wanted or needed, then the job absolutely requires a creative person. And if you have a creative person in place, and he is sufficiently interested in what you want him to do, then he _will be_ creative.

However, since creativity is inwardly generated by innate mechanisms, such creativity is not externally controllable and directable by normal social pressures, rewards, priorities. Both to get the best from a creative, and also to have that best be directed where desired, requires that the creative be animated, inspirited and energized by the task; and allowed to work in his own way.

Therefore a genius can neither be ‘managed’ nor ‘regulated’ – although he may to some extent be ‘led’ by a sufficiently inspiring and insightful individual
