# Successful Creativity

Now that we have an understanding of the creative person, his personality, and what motivates him, we must tease out the difference between the ‘creative’ and the genius. In essence, we argue that the creative genius is _a sub-species_ of the creative type, and the genuinely creative is characterized by the Endogenous personality type. So, the genius is the most successful and able and obvious type of ‘creative’ – and genius is an extreme form of creativity combined with other attributes (mainly exceptional ability, and especially with exceptional intelligence).

We have already proposed a correspondence between genius – understood as having an enormous impact in some field through highly original activity – and creativity. We would expect the genius to be ‘creative’ but there is a difference between being ‘creative’ (as it is commonly defined) and actually being original and insightful.

For example, people tend to think that poetry is intrinsically a creative activity – but we would emphasize that most self-styled or professionally-recognized poets are not especially creative, and that much greater creativity may be found among some people who are doing (for example) practical work, or caring for children than among the typical writer and publisher of poems.

In other words, properly understood, ‘poetry’ is a social function (a job, a hobby, an educational or academic task) which may be done more, or less, creatively – and this is probably the usual situation for most social roles. However, at the very highest level – a level that is at best rare and sometimes absent from society – poetry is indeed (of course!) a paradigm of creativity, and The Poet the epitome of genius.

What of originality? The originality of a creative person is likely to be achieved without being aimed at, through combining creativity with innate ability (in particular, intelligence) and a lack of concern about the reaction to one’s originality. Sometimes, in honest and creative pursuit of some goal (on a Quest), you need to break conventions and rules. The reaction to that which challenges the vested interests of the _status quo_ is generally negative – so creativity risks alienating powerful people and causing irritation or even hostility.

Therefore there is an _association_ between creativity and originality, and between originality and offensiveness. But, on the other hand, the opposite is untrue; so, it is _not_ true to say that that which causes irritation, offence and hostility is _therefore_ original; nor to say that what is original is _therefore_ creative.

Nonetheless, this falsely reversed causality has been the prevalent way in which creativity and originality have been identified in the modern era; for instance in the visual arts since the era of Dadaism about a century ago.[@31] In _avant garde_ circles, successfully provoking outrage (especially among ‘respectable’ people and the religious) has usually been regarded as sufficient evidence of originality, hence genius – leading to the ludicrous situation in which artistically-talentless confidence tricksters and public relations manipulators have successfully passed themselves off as artistic geniuses, and for three or four generations have dominated the professional world of Art.

Furthermore, in discussing creativity, a decision must be made as to whether we are going to give primacy to creative process or creative outcome. Not neglecting the other of the pair: but one of the two must come first.

We put process first – and therefore we discuss creativity as a disposition and process, and how these lead to what are generally regarded as creative outcomes. This opens a potential gap between creative activity and creative outcomes. So if a science Nobel Prize is regarded as a creative outcome, then we would say that some science Nobel Prize winners were highly creative persons – although some were not.

Some Nobelists seemingly got the prize in other ways: for instance by stealing or otherwise getting credit for the ideas or work of other people, or by careful and conscientious work extending the creative breakthroughs of others, or by self-promotion, or from lack of any really deserving prize-winners (this, especially, in recent years – when the supply of geniuses has all-but dried-up, and science has become more bureaucratic and less creative); or simply by errors or corruption or committee-think on the part of the Nobel prize committee.

And much the same would apply to great composers, great writers, great visual artists etc.

But if, instead, creativity is defined in terms of _process_, as a mode of thinking; then this means that many or most of the people who produce work (or outcomes) that are generally regarded as extremely useful, beautiful or true – are _not_ creative people.

For example, the work of British Nobelist Dorothy Hodgkin (1910-1994) was mostly a careful extension of the primary work of Desmond Bernal (1901-1971; her mentor and lover) – who was the real genius behind X-Ray Crystallography – but it was Hodgkin who did the work that got the prize. Significantly, Bernal had the classical genius temperament[@32] while Hodgkin – although extremely clever and skilful – showed hardly a spark of real ‘Endogenous’ creativity.[@33]

Furthermore, many or most creative people (‘creatives’) nowadays do not achieve anything that is generally regarded as useful, beautiful or true. We know of relatively unknown and unacknowledged ‘creatives’ who also have truly great abilities and are probably potential geniuses, but lack either the application or the luck to have made an influential breakthrough; or else their breakthroughs were not acknowledged as such. Indeed, some have suffered aggressive and harmful persecutions, such as professional harassment and mass media mobbing, for their honesty. For example, an insightful and original scientist working in an obscure branch of medicine, a major theoretician working in a field where only empirical and large scale research is valued...

Sometimes, the achievement of a genius seems to have hung by a thread; if British Nobellist and DNA-discoverer Francis Crick (1916-2004) had died at age 35, or had lived a generation later, he would have been regarded as one of these – merely a brilliant, restless, unfulfilled _dilettante_.

## The ‘evil genius’ phenomenon

It may happen that a highly creative person, by chance or design, deploys their creativity in such a way that it destroys their own field: a Picasso, a James Joyce, a Schoenberg… men of genius whose work was highly influential and brilliant, but who left their subjects and the world a worse place than they found it: they were each, artistically, a dead-end. These are versions of the ‘evil genius’ – so named because of their effects, rather than necessarily their motivations.

From the vantage point of creating something useful (to maintaining and developing civilization), beautiful or true, Pablo Picasso’s (1881-1973) artistic philosophy involved rejecting the idea that art should create beauty and a road to transcendence. His purpose was to challenge the accepted way of doing art and so challenge all that was established, including that which is useful. In so-doing, his art created a sense of shock, confusion, and meaninglessness and contributed to anarchy.[@34] The novels and stories of James Joyce (1882-1941) share much of this philosophy. _The Dubliners_, for example, horrified audiences with its detailed depictions of depraved behaviour and these actually occurring in real (named) streets and pubs. The stories take the reader into a world of nihilism and _Finnegan’s Wake_ simply creates a sense of ‘profound’ confusion.[@35] As for Arnold Schoenberg (1874-1951), he shunned musical harmony and tradition in favour of a highly-structured but incomprehensible kind of music which most people find it actively-unpleasant to listen to . . . a world in which nothing makes sense, there is no meaning, there is negativity, there is the Void.[@36]

So, these evil geniuses may or may not have had exceptionally wicked personalities, although all were somewhat unpleasant characters[@37] – but they did have a net-destructive effect on society. This effect was net-destructive because they advanced a compelling but destructive worldview; one which led to the suppression of, for example, the ability of people to perceive meaning and purpose in life, or active-encouragement of selfish, parasitic, or cruel behaviour.

Other examples might be philosophers such as Rousseau, Marx or Nietzsche.[@38] From the vantage point already outlined, the philosophy of Jean-Jacques Rousseau (1712-1778) rejected civilization in favour of a more ‘natural’ life modelled on a romantic-ideal of the tribe in which all were supposedly equal and free. This would be a dictatorship of ‘the people’ in which dissent, however, could not be tolerated; with dissenters labelled (in the Rousseau-influenced French Revolution) as ‘enemies of the people.’

Karl Marx’s (1818-1883) philosophy – heavily influenced by Rousseau – altered the idealized group from the ‘tribe’ to the ‘worker’ and argued that a worker’s dictatorship must inevitably develop to ensure equality based on Marx’s fate-based understanding of History. Again, dissent was not to be permitted and dissenters were ‘enemies,’ ‘imperialists’ and so on. Its culmination was the world-historical horror of twentieth century Communism, and its descendant Political Correct-ness, in which ‘the worker’ is replaced by supposedly oppressed or more natural ‘cultural’ groups. Dissenters are ‘racist’ and other catch-all, highly emotive terms (such as ‘hater’ or ‘denialist’) employed to discourage dissent, such that even the slightest deviance from orthodoxy is termed ‘racist’ in order to reprove it and intimidate the deviant into silence.[@39] These ideologies can distilled down to three essential dogmas: (1) Those who have power – whether financial or cultural and whether deserved or not – are bad and should repent by giving it to those who lack power and creating ‘equality’ (2) Those who lack power – on whatever measure is seen as important – are superior to those who have it because they are somehow more genuine and (3) Those who dissent from this view are wicked. As such, the dogma of ‘equality’ serves to create a ‘thought prison’ which would be antithetical to genius and, in both cases, the desires of a ‘natural group’ must be put before all else, including making the decisions required to maintain civilization.

Multiculturalism is related to Political Correctness, arguing that Western countries benefit from disempowering their cultural majority in favour of a cultural melting pot, and systematically privileging non-native ethnic groups. This is underpinned by cultural and moral relativism; and this brings us to the genius of F. W. Nietzsche (1844-1900).

Nietzsche’s work is complex, self-contradictory, evolving; esoteric and brilliant in style, of superb literary quality and shot-through with memorable, incisive insights. Nonetheless the _net_ effect of Nietzsche has been bad. He argued for a kind of moral and cultural relativism, or even a moral inversion by which traditional human values are reversed: what was evil becomes good and _vice versa_. The basic idea was that people in general, and the natural leaders of ‘Supermen’ in particular, should pursue their wild, instinctive, amoral dominant desires, helping them to be creative, life-affirming and to experience the heights of ecstasy. In _Beyond Good and Evil_, he clearly advocates moral relativism, arguing that what is ‘moral’ depends on whether you are a ‘master’ or a ‘servant.’ In _The Anti-Christ_, it is argued that the only ‘good’ is the gaining of power. So, in essence, Nietzsche advocates living an utterly selfish life in pursuit of one’s own power. Clearly, if everyone lived in such a way civilization would collapse and there would be no room to philosophize at all.[@40]

On top of this; Nietzsche’s sister edited, emphasized and altered his works to make them even more appealing to the embryonic National Socialists – eventually the Nazis came to regard his _Thus Spake Zarathustra_ as an equivalent of the Bible, and issued tens of thousands of copies to soldiers for their spiritual guidance… On the one hand, there is no doubt that Nietzsche himself would strongly have disapproved of this; on the other hand, it does not require much in the way of selection and distortion to extract Nazism from Nietzsche.

So it is not necessarily a compliment to call somebody creative or ‘a creative’ – really, it is simply a _description_ of a personality type.

Once we understand genius or high impact originality in terms of achievement, then there is a clear quantitative basis for asserting that a relationship exists between this and being disagreeable; and it is this combination of creativity, ability and being disagreeable which can lead to genius. American psychologist Dean Simonton has conducted a great deal of research on this subject and has found that academics who are considered highly original – and, indeed, recognized geniuses – tend to have distinctive personality features.[@41]

According to Simonton, geniuses usually have a personality type characterized by moderately high Psychoticism; that is: a psychosis-/ dream-like mode of thinking; indifference to public opinion; moderately low Agreeableness/ Empathizing and moderately low Conscientiousness. This, according to Simonton, is usually combined with high Openness-Intellect (strongly associated with creativity), and high Neuroticism (in the case of artistic geniuses) and high Extraversion (in the case of scientific geniuses).

As a reminder, we argue that this rather vague and complex constellation of statistical associations between traits can more parsimoniously, and validly, be conceptualized as the Endogenous personality. Furthermore, we will look below at how high levels of Neuroticism and Extraversion may actually be an artefact, due to the only-approximate validity of measuring what are inferred to be dispositional traits in terms of overt behaviour.

Both genius artists and scientists in turn combine this kind of personality with extremely high – outlier levels of – intelligence. Outlier intelligence occurs when chance combinations of genes in relatively intelligent parents lead to extreme intelligence in one of the offspring. Most children have intelligence at a similar level to the average of their parents; but it is quite possible for children to be far more – or less – intelligent than their parents, though this is rare. It is even rarer, though still possible, that average or even below average parents could produce a highly intelligent child.

Therefore genius is most frequently found among offspring of the most intelligent people, but can be found almost anywhere, albeit at lower frequencies.

This seems difficult to explain in the way that intelligence is normally considered – in terms of intelligence being a consequence of very large numbers (thousands?) of genes-for-intelligence. With intelligence genes conceptualized as additive in effect, and in such large numbers, it is hard to understand how a very highly intelligent child could emerge by chance from low-intelligence parents. But if a person’s level of intelligence is also determined by the number of deleterious mutations they inherit from their parents, and these mutations are numbered in tens – then it is imaginable that, by chance, a child may be born with very few deleterious mutations, despite his parents having a relatively heavy mutation load.

This notion is perhaps testable, on the basis that a low mutation load should be associated with generally higher fitness, and therefore with traits associated with high fitness – so the high intelligence child of low intelligence parents would be expected to be (on average) taller, healthier, more symmetrical, and more long-lived than his low intelligence parents.

The face and body have evolved to be symmetrical. Thus, facial symmetry shows that relatively few genetic mutations, which are almost always negative, have been inherited. It also shows that a symmetrical phenotype has been maintained in the face of disease, implying a genetically good immune system. Symmetrical people are, therefore, regarded as attractive because their appearance advertises their genetic good health.[@42] Studies have actually shown a weak positive correlation between intelligence and facial symmetry.[@43]

But, although highly intelligent children of less-intelligent parents have been, by chance, spared from the effects of deleterious mutations _on the brain_; nonetheless they would be likely to be carrying more deleterious mutations than the highly intelligent children of highly intelligent parents (because not all mutations affect the brain). So among the highly intelligent children of less intelligent parents, there might be evidence of relatively higher levels of other mutation-related dysfunctions – e.g. social maladaptiveness, psychosexual dysfunctions, psychiatric problems, fluctuating asymmetry or physical illnesses with a genetic basis.

It should also be noted that intelligence affects behaviour. High intelligence may act as a counterbalance to a personality type that would otherwise be associated with asocial behaviours characteristic of low General Factor of Personality (GFP). High IQ in a low GFP person provides a strong future orientation and self-control – due to a heightened ability to predict the consequences of their actions and a greater concern with the long-term[@44] – that such individuals would otherwise lack from their inherited personality traits.

Whereas with high intelligence a low GFP person may be merely a-social –uninterested by society; low GFP person and  low intelligence might well be _anti_-social – that is, significantly hostile, or actively socially destructive in their behaviour.
