# Identifying the Genius

When genius is defined as a type of person who evolved to benefit the group (by innovatively being able to solve novel problems and enhance social cohesion, survival and population growth), it can be understood that it is beneficial for societies to be able to _recognize and identify_ potential geniuses; so that they may be helped, tolerated; or at the least not actively attacked and suppressed.

But there has long been a confusion or blurring of the genius personality type with psychosis – with insanity: as in the phrase of English poet John Dryden (1631-1700): “Great wits to madness sure are near allied, and thin partitions do their bounds divide”. Furthermore, there is a relatively higher incidence of some forms of madness (especially melancholia and mania) and also alcoholism and drug abuse among geniuses and other creative people than among comparable control subjects.[45]

Yet we argue that creativity is not caused by madness, not even by partial degrees of psychosis – rather we argue that most madness is utterly uncreative, being maladaptive and caused by accidental pathology; while the root of creativity is to be found in the Endogenous personality, which is an adaptation that evolved to perform a valuable social function.

However, and this is a subtle but vital distinction, we acknowledge that there is indeed – as H. J. Eysenck described in his 1995 book _Genius_[46] – a higher than normal rate of psychotic illness, a higher than normal rate of psychopathic traits (which include low Agreeableness and low Conscientiousness but also more subtle characteristics)[47] and drug and alcohol problems among geniuses. We would explain this in terms of the Endogenous personality being an evolved adaptation for creativity, but one which is more than usually vulnerable to psychosis, psychopathy and drug addiction when there are further predisposing factors; genetic, environmental, social or whatever. But we regard the genius as being a specialized type arising as a result of evolution by natural selection; and therefore genius is _not_ – as Eysenck tended to think – a result of a partial degree of illness, antisocial personality, sickness or stress.

But the co-occurrence of madness and genius leads to a practical problem when trying to identify genius – how could we discriminate between uncreative insanity and the potential for creative genius? How can one tell if someone has the Endogenous personality type, rather than just being socially-_impaired_ for some reason? The difference is real and important.

To do this, we need to examine the Endogenous personality type in more detail. We have seen that there are two main aspects to genius: characteristic personality traits and outlier levels of high intelligence. We will begin with personality traits.

The Endogenous person has a strong inner motivation. He does not avoid groups and social responsibilities simply for negative reasons such as lack of interest, because he wants to do nothing; but because he wants to ‘‘do his own thing’’, because he is powerfully interested in some very specific thing.

The Endogenous person is therefore being _driven_ to do something. His mind is usually brooding on his ‘problem’, full of plans and aims and aspirations. These may or may not come to fruition – some people with an Endogenous personality are late-developers, and may superficially seem to be adrift, or to change direction too frequently to become successful; but they are actually _trying to find their subject_, trying to find their Destiny.

For example; Einstein did not shine at school and failed to achieve his first career aims, doing his first major work and completing a PhD in his spare time while employed as a Patent Office clerk.[48] Francis Crick (1916-2004) attended his second choice university (he was rejected from Cambridge so went to University College, London), achieved only a second class degree, started and gave-up two PhDs, and worked on naval research before he found what he ‘‘should’’ have been doing only in his mid-thirties, going on to co-discover the structure of DNA then making further fundamental contributions to unravelling the genetic code.[49]

Was there anything that could differentiate between drifting potential geniuses who have not yet found their destiny – people like the young Einstein and Crick; and people who are merely-drifting, starting and failing, unable to apply-themselves because they have something wrong with them?

## Extraversion- Introversion trait

What kind of personality results in such a disposition towards genius? We have already looked at the personality type seemingly associated with academics who are regarded as creative in their fields and, indeed, as geniuses in terms of the mainstream ‘Big Five’ traits.

There are, however, problems in measuring some of these traits when it comes to genius. In general, it would be expected that the genius ought to be high in the Introversion trait – in the sense that introverts are inner-stimulated and autonomous of their environment, in contrast with extraverts who depend on external stimulus to maintain a state of arousal or alertness.

But the self-rating scales for measuring Introversion focus on behaviours and not psychological mechanisms, focus on outcomes not processes – therefore those scoring high in Introversion will include people who are simply anhedonic (unable to experience pleasure), inactive; who lack motivation and drive – and these attributes would be fatal to the prospects of a genius accomplishing anything significant.

In other words, true, underlying Introversion would be a characteristic of genius, but a high score on the Introversion rating scale would also contain under-motivated people – thereby blurring the measurement by misclassification error.

Thus, a genius needs to be a genuine Introvert; but people with various pathologies might lead to ‘‘false positive’’ measures of high Introversion. This may explain the counter-intuitive finding that creative scientists are high in Extraversion – since geniuses are very rare, most of the high Introversion scores are contributed by those suffering from pathology.

## Neuroticism – Emotional Stability trait

Analogously, but in the opposite direction, high Neuroticism (N) would be bad for a genius, in the sense that N refers to an unpleasant and overwhelming sensitivity of emotions and moods to the environment – such that a high N person tends easily to be overwhelmed with negative emotions such as anxiety, shyness, low self-esteem, misery etc.

But the opposite state of low-N (or high Emotional Stability) as it is measured by behavioural questionnaires, is also potentially hostile to genius, since it implies an insensitivity to events; a lack of emotional-responsiveness – and low-N-scorers include people with weak emotions and people with emotional insensitivity. These would all tend to be a disadvantage to genius – since emotions are used to evaluate situations and evidence; so weak emotions would tend to impair discrimination.

These would be the underlying processes of Neuroticism, but in practice N is measured using a tally of (usually self-reported) ‘superficial’ behavioural traits – and these could not distinguish between different causes of the same behaviour; and so would conflate subtle and useful emotional sensitivity, with the pathological state of too-easy triggering of negative emotions.

So, a genius might score as somewhat high in N, simply because he experiences emotions strongly; but this would not necessarily reflect a pathological sensitivity.

## Psychoticism – Conscientiousness/ Agreeableness; and Agreeableness/ Empathizing

We have already seen that genius is associated with trait Psychoticism. The inverse correlation of Creativity in terms of Conscientiousness (C) and Agreeableness (A) is understandable, and necessary – once C and A are properly understood.

Creativity implies a strong ego, a person who looks at a situation and comes up with something different because he believes it possible – even probable – that he knows better than other people, and is (to some extent) indifferent to the opinions of others on this matter.

Why does this entail low C? Well, Conscientiousness is sometimes conceptualized in terms of delayed gratification – the ability to put-off gratification now, in return for greater gratification in the future. For example, to defer the pleasure of playing, and instead study academic subjects – foregoing the current pleasure of play, and suffering the tedium of work, for a (hoped for) greater pleasure in the future.

But this is an error – because it is not the way the mind is motivated. The mind actually works by maximizing _current_ gratification – by doing what is positively rewarding here and now, and avoiding what yields negative emotions. Therefore, the proper way to conceptualize Conscientiousness is that a high C person gets more gratification here and now by doing what he feels it is best to do, or necessary to do, or which he has been told to do by an authority, or what he is supposed to do according to peer pressure.

Therefore, high C implies a high degree of concern for internalized social norms – a tendency to feel good (here and now) when conforming to these social norms/ values – and/or a tendency to feel bad (e.g. guilty, ashamed, afraid) when transgressing or failing to follow these social norms.

And this is what links Conscientiousness to Agreeableness (or Simon Baron Cohen’s trait of Empathizing, which correlates highly with A).[50] High Agreeableness is a self-evaluation for having a dominating concern with the views of other people – paying close attention to knowing the emotions and wishes of others: that is, a calibration of one’s own (observed or perceived) behaviours to stay in line with the expectations or desires of others. Such a concern would be fatal to the chances of a genius attaining his Destiny.

So, it can be seen that Conscientiousness and Agreeableness are two sides of the same coin (and the inverse of Psychoticism) – which is that a person high in Conscientiousness and also Agreeableness is one who – here and now, and in the present moment – derives the greatest satisfaction from his conformity to the social group, and is attentive to cues of social group values: and (more important) who has aversive feelings if he transgresses or he fails to follow social norms, such as would happen if creative thinking was in play.

And such a person is _not_ creative – because he is focused on learning and doing what the social group wants him to do, instead of what his inner drives tell him he ought to do: needs to do.

## Creativity in low Psychoticism people

Although creativity is strongest in those high in the personality trait of Psychoticism (P) when combined with high intelligence (indicating a fundamentally functional and healthy brain), it is not restricted to those of high-P personality: probably, everyone is creative to some extent.

How then does creativity show itself in low-P individuals? – given that the distribution of Psychoticism within the population is ‘positively-skewed’ – in other words a majority of people are low in Psychoticism, and only a small proportion high in P?

In people low in Psychoticism, creativity is there but weak, seldom activated, not-dominant, short-lived and – as a rule – subordinated to social (including sexual) imperatives which are the primary drive for most people. Of course, almost by definition, creativity in the normal majority of people is not necessarily impressive, and is also rarely activated. So this low-level, relatively-infrequent creativity tends to be private, and almost invisible at a societal level (especially in large modern societies).

The easiest way to see low level creativity is perhaps in children – especially in older but pre-pubertal children (aged about 6-12), and their ‘crazes’ and hobbies. Boys often have very creative hobbies in which they become mini-experts and avid dissenters on such subjects as cars, aeroplanes, sports, dinosaurs etc. – also in reading (and memorizing) particular books (on favourite themes or by favourite authors), or TV series. These children often live chunks of their leisure time psychologically-inside a very intense parallel ‘fantasy world’.

Normal and average creativity is therefore seen in _hobbies_, and how people use their discretionary time; and the fact that hobbies are for most people subordinated to work, relationships and daily life is due to the low-P, low creativity personality.

Normal people are creative, to some subsidiary extent; and they fit creativity into their lives. But geniuses do the opposite: fit their lives around their hobbies; and geniuses usually make their hobbies (their avocations) into their life (their vocations).

## The Asocial genius

Humans are social animals: most Men see the world through social spectacles.

But a genius is not like this. The genius does not have a single, stereotypical, positive personality type (because Endogenous personalities are very various in terms of traits such as likeableness, helpfulness, and personal warmth) – but geniuses are characterised by _not_ being primarily social animals. A genius is one whose main focus and motivation is not social, nor sexual; but instead abstract, asocial – whether artistic, scientific, technical, or whatever it may be.

Could it then be that the genius uses for abstract thinking, those brain-systems which in most people are used for social intelligence? That in the genius the social intelligence system is wired-up to internal stimuli instead of to social situations? It seems that the genius deploys the social intelligence parts of the brain for other purposes – and that therefore the usual spontaneous motivation and attention that goes to social material is instead – automatically – being harnessed and deployed to deal with other and inner-generated material. This seems to us very likely; although such aspects of brain structure have not yet been reliably measured. But given that the genius brain seems to be hard-wired for both creativity and intelligence; it is plausible that this may be made possible by functional re-deployment of at least some aspects of social/ sexual circuitry.

So, it is not that geniuses lack social intelligence (the genius is not ‘autistic’ in the sense of having a deficit or defect in social intelligence); rather that geniuses have all the ‘equipment’ necessary for social intelligence, but are ‘wired-up’ to use their social intelligence for other and not-social purposes.

Specifically, the genius’s social intelligence may be wired-up to internally-generated material (instead of attending to actual people in the environment and from memory). The spontaneous interest and concern with ‘‘other people’’ that is characteristic of most people is, in the genius, directed to whatever ‘abstract’ subject the genius has a vocation-for.

Another way of thinking about this is that the genius may be able to deploy extra ‘‘brain power’’ in problem solving, by ‘‘co-opting’’ the brain regions normally used for social intelligence. And not only brain power – but the distinctive ‘‘theory of mind’’ mode of thinking which characterises social intelligence. So the genius often thinks about ‘‘his subject’’ in a social-like way – as a world populated by entities with motivations and dispositions and each having a purpose.

Social intelligence could be much of what is creative about creativity; because to think about abstract things ‘anthropomorphically’ with social intelligence, or animistically as if they were sentient social agents, perhaps opens-up a new and probably more creative, intuitive and flexible way of thinking.[51]

The Endogenous personality also has very high intelligence. This may be apparent through good exam results in a ‘g’-loaded evaluation, but may require formal intelligence testing to detect, if the individual has either suffered from poor or absent education, or else lacks the conscientiousness to apply himself to his studies. And sometimes intelligence tests won’t do justice to the genius’s abilities.

That the intelligence of the Endogenous Personality can sometimes not be identified in a conventional way is of crucial importance. Often, the genius will have extremely pronounced abilities in one area of intelligence – such as verbal intelligence – but will be less skilled in other areas. Einstein, for example, had such high mathematical abilities that he developed an original proof of Pythagoras’ theorem at the age of 12. However, his linguistic abilities were so deficient that he failed the entrance exam for the Federal Institute of Technology in Zurich.[52] Consequently, though an IQ test can capture general intelligence it will not necessarily be able to capture genuine genius.

So, the Endogenous personality may be recognized not just by their relative autonomy – that is, their lack of need for social validation and consequent lack of interest in social and sexual matters – but also by their high intelligence and positive motivation to do (or to find) ... whatever it is that they are equipped by their nature to do.
