# Destiny versus Conscientiousness

The Creative Triad is a minimum requirement, of course, and there are other features that may help to identify a genius. One of the marked features of the Endogenous Personality is a sense of Destiny. This leads to a Quest and, eventually, Illumination. We are prone to think of only the last step in this journey: the _Eureka_ moment’ of Illumination when the genius is flooded with insight and sees the answer to his problem, and what the answer means. But there are at least three distinct phases of which this comes late.

## 1. Destiny {-}

From childhood, youth or early adult life there is a sense of destiny, of having some special role to play. This destiny is accepted, not chosen; so that the task is not to manufacture, invent or devise a destiny; but rather to discover, to find-out the nature of one’s own personal and unique destiny. Such a process of discovery is a matter of trial and error, following hunches, drifting; false leads, blind alleys and red herrings – there is no recipe for finding one’s destiny. Nobody else can do it for you.

## 2. Quest {-}

After seeking, the genius recognises what it is that he is meant to do (or, meant to attempt): this is his Quest. Now he has to choose – does he embrace his Destiny and accept the Quest? – Or does he refuse? Only he can decide; and he will inevitably decide: the decision is unavoidable.

## 3. Illumination {-}

After prolonged effort – months, years, a decade or more: _Eureka_ moment – Illumination is achieved: the thing is done! (_Eureka_ means something like “I have found it!” and is attributed to Archimedes in his bath.)

The experience accumulated, the skills gained, the understanding achieved during the Quest at last come together and the breakthrough is made. A textbook example would be the English architect Michael Ventris (1922-1956). Ventris was plagued by ill-health as a child (he also suffered from night-blindness and extreme short-sightedness) but was blessed with an ability to learn languages. He met the archaeologist Sir Arthur Evans (1851-1941) on a school trip to the Royal Academy in London in 1936, when Ventris was 14. Evans held up some Cretan tablets, written in Linear B script, declaring that nobody could decipher this. Ventris dedicated the rest of his life to cracking Linear B. Ventris finally succeeded in 1952, after which he was reported to lack a sense of purpose. He died in a night time car crash in 1956, aged 34.[@53]

Of course there are other phases coming after Illumination – for instance the Illumination must be communicated to others; but beyond a certain minimal effort at recording, reproducing and revealing, effective communication is often ‘in the lap of the gods’ – and beyond the scope of purposive activities of the genius. Then the Illumination must be understood, considered, implemented, and so on.

The usual life of an Endogenous personality is in stark contrast to that of a Conscientious person, helping us to identify who is closer-to and who is further from genius. The Conscientious personality is driven by external social perceptions – he is attuned to peer pressure, he accepts peer evaluations, and may work hard on problems and jobs which are derived from the social _milieu_.

The Conscientious personality has not chosen his problem; more exactly his problem does not derive from inner sources. He is motivated to act – but by other people, not by trying to solve his own ‘problem.’ The Conscientious personality has no sense of being on a track of Destiny; he does not ‘own’ the problem he is working-on. That line of work may be adopted from obedience, or duty – or as a matter of expediency (e.g. for status, or money, or to get sex). But when a line of work ceases to be externally required, or is externally discouraged, or becomes inexpedient then it will be abandoned.

From this it is clear that the Conscientious personality is not suited to a genius, is un-original and unlikely to lead to breakthroughs. He has the drive to do something in the world; but that something does not derive from within him, and therefore does not mobilize his full inner resources. And his motivation will fail when times are tough – he will not push through discouragements.

In contrast to the externally-orientated Conscientious personality, the Contemplative personality is focused upon the inner world. The mind’s eye is turned inward; and the Contemplative personality is meditative; occupied by thoughts, fantasies, speculations ...
However, the contemplative personality is not creative but ... contemplative. For a Contemplative, ‘action’ is meditative – understanding, experience, the observation of the transcendental such as truth, beauty, virtue, unity... this is what provides the greatest satisfaction.

The Contemplative personality is a dream-er, not a do-er. Therefore, the Contemplative will not summon the long-term, stubborn determination required to do genius-type creative work; the Quest to keep pushing and pushing at a problem until it yields to Illumination – then to communicate the outcome.

The Contemplative personality has the kind of autonomy of ‘public opinion’ which is necessary to creativity – but lacks motivation towards actions, lacks the ‘drive’ to solve a problem – instead he is content to contemplate perceived reality rather than to re-conceptualize reality.
