# The Shaman versus the Head Girl

## Power, Pre-eminence, Personality

In considering the nature of genius, it is not possible to define it in terms of a single variable – but it requires several factors: the three Ps – 1. *Power*, 2. *Pre-eminence*, and 3. *Being associated with a Personality*.

### Power

Genius is a form of power. It is indeed a new source of power that adds to human capability. An analogy would be that genius is like discovering a new supply of fuel – a new forest, coal seam or oil field. This new power can be used constructively, or destructively – for tools or for weapons; and a weapon can be used for legitimate defence or for malicious torture.

Genius is somewhat like _a local reorganization of reality_ to create new capability or efficiency or effect, the insights and theory necessary for such a reorganization, or a technology or tool that enables such a reorganization.

But if the primary reality of genius is a new source of power, the secondary effect is to redistribute power – specifically to concentrate power around the results of genius (not necessarily around the genius himself, but concentrate power around the product of genius). But it should be noticed that the tendency is for this power to diffuse and disseminate – so that the consequences of genius typically spread much more widely than the situation or society in which the originating genius dwelt.

For example, technologies such as the architectural arch (inventor unknown) spread rapidly and widely across Europe and Asia Minor. The opposite situation, when a breakthrough is confined to the originating group, is rare but does sometimes happen; one example is Greek Fire (inventor unknown) – which was a substance used as a deadly incendiary weapon by the Byzantine Empire, that could continue burning even while floating on water – the secret recipe for which has never been discovered.

### Pre-eminence

The power of genius is associated with pre-eminence. A genius must also be pre-eminent in his field, must be a person of high ability. Thus, it is not genius when a person is of mediocre ability but merely has power conferred upon him, or has a large effect, but by accident.

### Personal

Genius is personal; that is, it originates in a specific person. The power and pre-eminence of a genius must also be derived from within themselves, must originate from the person – and not merely from his position in a system or institution or from headship of a team (or from some other person – as when somebody else’s work is appropriated).

## The Shaman

So, if we want a useful metaphor; the power of the genius is like that of the shaman, in contrast to that of the chief. The power of the genius is like that of German sociologist Max Weber’s (1864-1920) ‘Charismatic’ in contrast to the ‘Bureaucrat’[54] who then administers the society which the Charismatic (the one with the gifts to make a cold world seem warm) has founded. The genius may impress her teachers at school, but she is not going to be made Head Girl.

The shaman comparison is, perhaps, the most useful. Now, the category of shaman is a modern, Western conceptualization which unifies disparate figures found in a wide range of tribal situations and from different historical times. The term was originally Siberian and this may link culturally to Amerindian examples (including among Eskimos/Inuit, through classic ‘Red Indians’/ Native Americans; to Amazonians and Patagonians); but shamans are also instanced among the Bushmen of the Kalahari desert in Africa and Aborigines in Australia; and indeed wherever there is an animistic, or simple totemistic (where an animal totem is worshipped and sacrificed) religion. The shaman lives in a world dominated by spirits, everything in the world has its own spirit and that spirit must be appeased through ritual. He has the ability to enter the spirit world, negotiate with the spirits, and so improve the life of the tribe through healing or ensuring good hunting.[55]

As such, despite the many fair points made by revisionists which tend to suggest that the whole area of shamans is so vague and confused that it would be better to dispense with the term; we believe it does have value. The key point is that shamans were unexpected figures for anthropologists – found in some types of simple society; but apparently either completely absent from Western societies – or else hidden so deeply as to be undetectable by official investigators. So anthropologists might have expected to find priests, analogous to the already known priests of the Western, Middle Eastern and Far Eastern societies – but shamans were not priests. A new category was needed.

What do shamans do? They are called upon to deal with exceptional situations – situations where there is no traditional guidance, or where the traditional guidance has been tried and found to be ineffective. Such situations could include some types of illness, when and where to move for better hunting, what to do about threats from predators or other tribes, ‘legal’ judgement in difficult cases – many types of advice and guidance, interpretation and prophecy.

To do this, shamans use altered states of consciousness – trance states of various types or visionary dreams – during which shamans contact the underlying spirit world for information and prediction, or to intervene and change things. In a nutshell, shamans are believed to be able to come into contact with a deeper level of reality than the everyday – and that is the source of their abilities – and their societal role.

So, shamans are highly creative persons – and therefore we would expect that they would show the Psychoticism-like traits of high creativity; and this seems to be confirmed by anthropological accounts. Shamans usually emerge from an early age of life – either childhood or teens; the shaman is either marked from an early age as being different, or else goes through a (typically) traumatic experience of illness, accident or some other stress, which changes them permanently. Thus, shamans are seen as flawed, damaged people who also (because of this, not despite it) have special gifts.[56] They are the ‘wounded healers’ as the Dutch Catholic priest Fr. Henri Nouwen (1932-1996) put it.[57]

The shaman is usually a man – usually not socially integrated, usually lives somewhat apart, may be unfriendly – a person feared and respected rather than loved and cherished. Often the shaman is unmarried, without known children – someone who hands on his social role by apprenticeship rather than founding a lineage. Someone who does not work, but is supported by payments for services and charity/protection money – at least he does not do work as it applies to the rest of the tribe – hunting gathering, agriculture, warfare, child care.[58]

It would obviously help if the shaman was more-than-usually intelligent as well as more-than-usually creative – but it is probable that these nomadic, simple hunter-gatherer societies have not been selected for higher intelligence over hundreds of years – as have some of the more stable and more complex agricultural societies (as we will see later).

So the objective intelligence of real life shamans may have been relatively lower than what Europeans of recent generations would have considered to be average. However, it is likely that shamans were relatively highly intelligent by the standards of their people.

But it is not only the exceptional intelligence that sets the shaman apart – rather it is the different cognitive style: the shaman approaches problems differently, or creatively as we would say – he does not apply the usual, traditional, high status or socially sanctioned rules or practices; but instead generates his unpredictable answers using quite different processes and procedures.

And this is something that the shaman cannot help doing: he is made that way, he is called to a role. The shaman is probably an Endogenous personality; he embodies that power which comes from high ability combined with high creativity, and it is this which enables him to serve a crucial social function in certain rare but important situations. Most of the time he is not wanted, scary, chaotic, nasty, a nuisance, a parasite – but there are situations when he is needed. And it is for these situations that the shaman is protected by the rest of the tribe.
This, then, is the same kind of power the genius has: the shaman can be considered an example of the ‘local genius’.

## The Head Girl

As already mentioned, a comparison, or anti-comparison, with genius is the ‘Head Girl.’

The first issue is simply this word ‘Girl.’ Genius tends to more common in males. There are a number of reasons for this:

1. Women’s intelligence is more bunched towards the mean than male intelligence, meaning there are more intelligence outliers among men.

2. Adult men probably have a moderately higher average IQ score than women (perhaps one third of a standard deviation higher) – which (like the wider standard deviation of male IQ) also translates to a more substantial proportion of men at the very highest levels of intelligence.[59]

3. In surveys, men are nearly always rated higher than women in average Psychoticism; and people with high levels of Psychoticism are much more likely to be men than women (the distribution of Psychoticism is positively-skewed in most studies – that is most people have low levels of P, and only a small proportion have high levels). We would interpret this sex difference as partly being due to higher rates of psychopathy/ ‘psychopathic personality disorder’ in men; but partly also an aspect of the more creative, Endogenous, personality type.[60]

It is noticeable that girls’ crazes tend to be more socially-inflected and less abstract (e.g. princesses, fairies, clothes, ponies); and this follows through to adult life, and to the subjects of major achievement for women. The highest frequency of genius-level, or near-genius level, achievement among women is focused on the most social and human aspects of the arts and sciences – and much rarer in abstract areas. For instance, there are many and well known women novelists in the front rank (notably Jane Austen and George Eliot) – the novel being the most ‘social’ of art forms. And in science, the highest achievements of women are in the human sciences rather than the physical sciences – and within biology women have been very prominent in social areas like primatology (e.g. Jane Goodall, Sarah Blaffer Hrdy) and anthropology (e.g. Ruth Benedict, Jane Jacobs).

It is a tenet of feminist ‘scholarship’ that there were many women geniuses who were neglected because they were women; and a large part of feminist scholarship has been dedicated to raising awareness of women geniuses. That there are indeed women geniuses is clear – examples abound, especially in literature; but we do not think feminist scholarship of the past fifty years has come up with a single ‘neglected’ example of a major woman genius.

Instead there has been a combination of the pretence that real women geniuses were ‘previously neglected’ until feminism came along; plus the hyping of women non-geniuses (such as Hildegard of Bingen as a composer and spiritual writer, the DNA scientist Rosalind Franklin, and playwright Aphra Benn). But Feminist scholarship has failed to discover any real women geniuses, because there have been relatively few.

The ‘Head Girl’ is thus even more problematic in terms of genius. The stereotypical Head Girl is an all-rounder: performs extremely well in all school subjects and has a very high ‘Grade Point Average’ as it is termed in the USA. She is excellent at sports, Captaining all the major teams. She is also pretty, popular, sociable and well-behaved.

The Head Girl will probably be a big success in life, in whatever terms being a big success happens to be framed (she will gravitate towards such aspects of life) – so she might in some times and places make a good marriage and do a great job of raising a family; in another time and place she might go to a top-notch college and get a top-notch job – and pursue a glamorous and infertile lifestyle of ‘serial monogamy’; with desirable mates.

But the Head Girl is not, cannot be, a creative genius. The genius is pretty much everything the Head Girl is not. He (or she) is lop-sided in his abilities – truly excellent at some things or maybe just one thing, he is either hopeless or bored by many others. He won’t work hard for long periods at things he does not want to do. He will not gravitate to the prestige areas of life and cannot, or will not, do the networking necessary to get-on.

The Head Girl can never be a creative genius because she does what other people want by the standards they most value. She will work harder and at a higher standard in doing whatever it is that social pressure tells her to do – and she will do this by whatever social standards prevail, only more thoroughly. Meanwhile the creative genius will do what he does because he must.

The Head Girl will not want to alienate potentially powerful allies. Meanwhile the creative genius is indifferent or hostile to the opinions of others so long as he knows he is right.

The Head Girl is great to have around, everybody thinks she is wonderful. Meanwhile the creative genius is at best a person who divides opinion, strongly, in both directions – at worst often a signed-up member of the awkward squad.

### The vulnerable genius

The proper social role of the highly able Endogenous personality is not as leader. Indeed, the Endogenous personality should be excluded from leadership as he will tend to lack the desire to cooperate with or care for the feelings of others. His role should be as an intuitive/ inspired ‘adviser’ of rulers.

Adviser-of-rulers is a term which should be taken to include various types of prophet, shaman, genius, wizard, hermit, and holy fool – the Socrates of the early Platonic dialogues is an historical example, as is Diogenes, the Cynic, of Sinope (c.412-323 BC), who lived in a barrel and is supposed to have snubbed Alexander the Great (without being punished), or even the Fool character in Shakespeare plays.

These are extremes; but the description of Endogenous personality and of an ‘inner orientation’ also applies to most historical examples of creative genius. The Endogenous personality – therefore – does not (as most men) seek primarily for social, sexual or economic success; instead the Endogenous personality wants to live by his inner imperatives.

The way it is supposed-to-work, the ‘deal’, the ‘social contract’; is that the Endogenous personality, by his non-social orientation, is working for the benefit of society as a whole; at the cost of his not competing in the usual status competitions within that society. His ‘reward’ is simply to be allowed, or – better – actively enabled, to have the minimal necessary sustenance, psychological support (principally being ‘left alone’ and not harassed or molested; but ideally sustained by his family, spouse, patron or the like) to be somehow provided-with the time and space and wherewithal to do his work and communicate the outcome. For the Endogenous personality, this is its own reward.

In return, the Endogenous personality should not expect (although he might, by chance, get) social esteem, wealth, or sexual success. Often, he may need to be highly solitary, secluded, ascetic, perhaps celibate. He should not seek, and should try not to accept, leadership positions, or administrative responsibilities.

Michael A. Woodley makes the point that individuals who can properly be classified as geniuses necessarily have brains that are wired differently from normal; they are programmed to focus on their destined tasks and therefore may be unable to deal with the small details of day to day affairs.[61] For instance, Einstein once got lost not far from his home in Princeton, New Jersey. He went into a shop and said, ‘Hi, I’m Einstein, can you take me home please?’ He could not drive a car, and many tasks and chores that most people take for granted were beyond him.[62]

Woodley’s conclusion flows from the idea of genius as a group-selected trait adapted to be an asset to other people. In sum, the potential genius needs to be looked after; because in terms of negotiating the complexities of human society he is likely to be vulnerable and fragile. The corollary of which is that when geniuses are _not_ looked after, they are less likely to fulfil their potential, and everybody loses.

For instance, the American reclusive poet Emily Dickinson (1830-1886) was ‘managed’ by Colonel T.W. Higginson; Jane Austen (1775-1817) flourished in the obscurity of her family and the critic and social philosopher John Ruskin (1819-1900) was sheltered and nurtured by his parents, then a cousin. Thomas Aquinas (1225-1274) was looked after by his brother Friars; Genetics-founder Johann Mendel (1822-1884) was secluded in a monastery; Pascal (1623-1662) was looked after by his aristocratic French family.[63] Plus many another genius was sustained by a capable wife – Kurt Gödel (1906-1978) depended on his, older, wife Adele; and would only eat food prepared by her; so that when she was hospitalized, Gödel literally starved.[64]

When there is a close-knit and idealistic community, this may also do it – for example, the community of mathematicians looked after Hungarian Paul Erdos (1913-1996), who never had a home, possessed only the contents of a small suitcase, and camped-out at in the house of one mathematics professor after another for decades, while collaborating on research papers. The Indian genius mathematician Srinivasa Ramanujan (1887-1920) was discovered and protected by the Cambridge Professors Hardy and Littlewood – although he died, weakened by his inability to eat adequately due to Brahmin dietary restrictions that were too rigorous for English life.

The unfortunate William Sidis (1898-1944), an American child prodigy of the early twentieth century and reputed to have the highest ever recorded IQ score; was exploited and exposed to social stresses rather than protected by his parents (his father was a Harvard professor of Psychology). Sidis was a sensitive and awkward man who had to survive in a hostile and mocking world; so his creative achievements – although greater than commonly supposed – were limited, and indeed largely unknown and unappreciated.[65] 

## The rise of bureaucracy

Modern society is dominated by ‘bureaucracy’, that is by division of function, voting committees and formal procedures – rather than by individual humans, close-knit and informal groups making personal judgments.

This impersonality of bureaucracy, the lack of individual autonomy and responsibility; seems to be a major factor in the modern failure to look-after, but instead to neglect or even to persecute, geniuses.

Furthermore, in itself, the rise in bureaucracy – in academia and also more broadly – might be seen as further evidence of the trend for decline in intelligence. There are a number of complementary explanations for the rise in bureaucracy which would be congruent with this theory.

### 1. Parasitism {-}

Bureaucracy can be seen as a parasite, growing at the expense of the host society. Some bureaucracy is necessary as society becomes more complex and organizations become larger. However, the abundance of wealth and resources created by industrialization has meant that it is possible for a group of quite unnecessary people – e.g. micro-managing and inefficiency-generating bureaucrats – to latch onto the host and even persuade the host that they are necessary. Once attached to the host they spread like a cancer because criticism of bureaucracy leads to further ‘regulatory’ bureaucracy to sort-out the bureaucracy. A more intelligent host would realise that the bureaucracy was parasitic and would remove it – but once the bureaucracy is large enough, then it will dominate all senior positions and committees, and become impossible to excise. At that point, death of the host – along with the parasite – becomes almost inevitable. [66]

### 2. Division of Labour {-}

Bureaucracy tends to involve an increasing division of labour and the assumption that the decision of a committee will be superior to the (potentially corrupt) decision of an individual. Such division and oversight functions would be more necessary in a society with declining intelligence, because individual decisions would be more prone to corruption and plain stupidity than in a more intelligent society; and people in general would be less likely to trust individuals as intelligence predicts trust.[67] Accordingly, in the context of universities, for example, there would increasingly be a need for more rigid and impersonal personnel selection in the form of requiring formal qualifications achieved _via_ rigid criteria. In addition, bureaucracy includes breaking up a task into smaller component functions coordinated in a hierarchical sequence. It takes less intelligence to perform these smaller functions than the entire specialised task. Thus, as society becomes less intelligent so greater bureaucracy is required for even necessary bureaucracy to continue (or for parasitic bureaucracy to continue to grow).

### 3. The Growth of Academia {-}

As society has become specialised, academia has grown enormously; initially from social need, later from the parasitic growth of functionally redundant and ineffective demands for certification – sustained by increasing state subsidies. As the academic staffing of ever-more institutions expands many-fold, the intelligence range of academics is likely to become far broader than it once was, and the tail of less able academics comes to dominate numerically. In addition, the population trend of declining intelligence will mean that even the best academics will be less intelligent than a generation ago. As such, a larger and more effective bureaucracy apparently becomes more necessary (or, at least, desirable) to police and manage a less intelligent (and less self-motivated) academia; which is likely to be increasingly corrupt, incompetent and factious. In addition, we have seen that intelligence correlates with ‘Intellect’, and universities have become far less intellectual. Instead of acting primarily as a specialist intellectual ‘finishing school’, they train people – either partially or completely – for various professions: solicitor, engineer, school teacher, government administrator, private industry managers of many types, architect, accountant etc. Until as recently as the 1970s, none of these required a degree – now they do; as do a multitude of skilled manual jobs like pharmacy, physiotherapy, nursing etc. This can be seen to herald a change in attitude. Universities were primarily about training professionals which were originally priests, barristers and physicians only – but the notion of ‘profession’ has been expanded a hundredfold; and now a university degree is a pre-requisite for even reasonably-paid jobs – unrelated to the actual needs of those jobs. This will select for students who are better at attaining qualifications, at working in a bureaucracy; hence the selection procedures favour those who are Conscientious rather than geniuses.

### 4. The Only Means of Achievement {-}

We have seen that academic achievement is partly predicted by intelligence and partly predicted by personality traits, especially Conscientiousness, which predicts years spent in education at 0.55.[68] Accordingly, in principle, someone can get into a good university _via_ 1. The combination of very high intelligence but only moderate Conscientiousness, 2. Very high Conscientiousness but only moderate intelligence or 3. By scoring reasonably highly on both measures. Bureaucracy – the keeping of records, planning, and adherence to formal procedures (the qualities of a Conscientious person in many ways) – should be smaller, at any given stage of complexity, the more intelligent (on average) is a given society. This is because intelligence reflects a high functioning brain and thus superior memory (swifter learning and less need to record things), superior ability to solve any given problem (and so less need for formal procedures and planning), and being more functionally pro-social and more forward-thinking (meaning less conflict, less free-riding, more trust, and fewer unforeseen problems to manage). Thus, as society becomes less intelligent it can only maintain its achievement level through more Conscientious behaviour: that is, through more bureaucracy.

But, whatever is behind the growth in bureaucracy, whatever mixture of need and parasitism that might prevail in any particular time and place, it leads to decision by committees of bureaucrats who will implicitly be looking for people who will make good bureaucrats and often who will make a university money in the relatively short term. They will not want people who will upset the smooth functioning of the bureaucracy – which genius types may well do – and they will be rigid in sticking to rules, which geniuses won’t be. It will also be very difficult to punish bureaucrats in voting committees for making a poor decision – for instance, rejecting a person who later turns-out to be a genius in the field, and whose appointment would therefore have eventually paid-off – as rejection was a collective decision where they merely followed the rules; also the composition of the decision-making committee is (typically) unstable and constantly changing. Moreover, bureaucratic “sticking to the rules” will typically work against geniuses, because bureaucrats usually have a black-and-white interest in qualifications, grades and the like. This will be problematic for the genius, with his highly narrow, lop-sided focus. (We have noted elsewhere that Newton, Einstein, Crick and many another genius did not excel academically by formal criteria).

In sum, committees do not look after geniuses – rather they ignore them, or persecute them. It is likely no coincidence that English genius very suddenly all-but disappeared in the era from about 1955-1980[69] in which bureaucracy waxed dominant in national life – and nowadays geniuses are absent, invisible, or fighting for survival against the forces of mass media, committees, peer reviewers and other faceless officials.

This is sad for the geniuses; perhaps fatal for our society.
