# Newton versus Jung

To further illustrate the nature of genius, it will be useful to explore two examples. The first is Sir Isaac Newton (1642-1727); a genius, and one of the very greatest.[70] The second is Carl Jung (1875-1961), who displayed aspects of genius; perhaps a highly influential partial genius.[71]

Newton’s intellectual ability, his intelligence, was very obviously stratospheric; so his personality becomes a source of fascination. Hans Eysenck established that the high level creative personality type was approximated by the trait of High Psychoticism, which we have already discussed.

Newton’s biography reveals that he was an extreme example of the Psychoticism trait. Psychoticism is important to genius because it describes someone who is uninterested and uninfluenced by the normal human concerns – which are essentially ‘other people.’ Most humans are social animals, who see life through social spectacles, and who are motivated by the desire for friends, sex, status, and so on. But not Newton. In his early and most creative years, he simply wanted to be allowed to get on with his work.

As a child and young man of science he would spend nearly all of his time alone, when in company he would be silent, he had essentially no friends, formed no relationships with women, and made very little effort to fit-in. Indeed as a boy his relationships with other boys tended to be antagonistic and at times rather sadistic (Newton was not likeable).

Newton was taught Latin at school; and little else. In terms of mathematics and science he was an autodidact. Whatever he did, he did because he wanted to do it; and he did it at close to 100 per cent effort. Thus in a year or so he went from knowing no mathematics to mastering the subject and being among the best in the world; and then immediately went on to make some of the greatest ever mathematical discoveries.

Newton’s own explanation of his achievement emphasized the distinctive creative personality – he was asked how he made his discoveries and gave such answers as ‘By thinking on it continually’ and ‘I keep the subject constantly before me’.

Then he all-but dropped mathematics, and instead worked on one area of physics after another – making major discoveries, then moving-on. This may remind you of the ‘schoolboy crazes’ or obsessions, typical of some highly intelligent young men.

Stories of Newton’s consuming focus abound – he would think solidly for hour upon hour – sometimes standing lost in abstraction half way down the stairs; forget to eat, forget to sleep; forget that he had visitors. For years he seldom left his college, almost never left Cambridge. In all of human history there can have been very few (and perhaps nobody of Newton’s astonishing intelligence) who gave such intense and sustained concentration to whatever problem they were working on.

And while Newton’s academic performance was good, it was not amazing, and was somewhat erratic. It seems he performed badly in his BA examination – which was a _viva voce_ disputation; needing to go on to a second round of questions (rather than passing straight away). This was regarded as somewhat disgraceful.

His methods were highly intuitive, reasoning from a relatively small base of axioms and principles, building out from them, making predictions and testing his ideas against general observations. This can be contrasted with the method typical of highly intelligent and conscientious _un_-creative people – who read widely, learn many facts, and then try to apply other-people’s solutions to problems.

But Newton, the autodidact, worked things through for himself; thought things through using only those facts and principles he trusted. From this; originality follows quite naturally and without being deliberately sought.

It is clear that Newton’s solitary, wilful and autonomous personality; his un-empathic, un-conscientious, anti-social and eccentric ways – in sum his high Psychoticism traits – were as necessary a part of his supreme genius as was ultra-high intelligence.

Let us now contrast Newton with Jung. Carl Jung is unusual among probable-geniuses, in that he was dishonest about his own work and its implications.

That Jung was a near-genius we think is correct; he made numerous discoveries and conceptual breakthroughs – and he is an unseen but pervasive influence behind vast areas of modern culture including psychology, psychiatry, therapy and (especially) that vast and vague phenomenon called the New Age movement (almost everything about the New Age has a Jungian lineage – even when this is not generally known or acknowledged).

But that Jung was a thoroughly-dishonest and deceptive man is something equally undeniable. Jung was never plain and honest when that was inexpedient – Jung was not driven by a pure pursuit of truth; because truth was readily and repeatedly sacrificed when the consequences were unwanted by Jung. (Eysenck regarded lying as typical of the high Psychoticism personality.)

He craved respectability as a Professor, psychiatrist, scholar, scientist – and would trim his published views to ensure this. He wanted wealth, status, admiration – and patients were charmed, seduced, strung-along and generally exploited to ensure this. Jung wanted to be regarded as an unworldly sage – but worked to create an organization dedicated to his own self-promotion. He apparently had many sexual relationships with his patients and trainees right into old age; and had a long-term live-in mistress who functioned as a second wife (while being unmentioned in his autobiography – he also used his personal magnetism to maintain a household of handmaidens to dote upon and serve him).

The point is that Jung’s many compromises, deceptions, evasions, and lies are so consistently dedicated to his own comfort, convenience and gratification that the picture is one of a highly charming and dominant; but heartless, manipulative and selfish psychopath – typical traits of high Psychoticism, but which interfere with creative achievement. Furthermore, Jung experienced a significant psychotic episode (his ‘confrontation with the unconscious, from 1913) characterized by hallucinations and probably delusions.

In sum, Jung – like Newton – exhibited some aspects of the dark side of Psychoticism.

Jung is, in several respects, the precursor of the postmodern intellectual – the ‘clever silly’ who espouses an illogical, incoherent, dogmatic, opaquely expressed, and overly complex idea. Doing this helps him to display his intelligence – because the idea is complex and hard to understand, making him seem profound to silly or emotional people – even if the idea is nonsense on closer inspection. Also, if the idea gives people hope, then he will come across as altruistic, further boosting his status.[72]

But this could be put aside as mere hypocrisy – and that is something of which we are all guilty (it would be hypocritical to pretend otherwise). But Jung’s dishonesty went even deeper than that, to invade his primary achievement. Because Jung’s work is incoherent at the very deepest level – and this incoherence has afflicted his legacy. And this incoherence was not the result of confusion, but the result of dishonesty.

An example is the idea of synchronicity; which has become an extremely influential cultural idea, as a buzz-word and a vague concept – but which was deployed by Jung in a way that makes no sense. And this incoherence is not due to misunderstanding Jung, but comes directly from Jung’s written contradictory accounts and evasions of the implications of his own insight.

British philosopher Colin Wilson (1931-2013) exposed this in his marvellously insightful short study: _Lord of the Underworld: Jung and the Twentieth Century_ (1984); especially the chapter “The Sage of Kusnacht”, where Wilson goes through the writings on synchronicity with a fine-toothed comb, and tries to pin down what Jung really believed, or meant – and comes up against a mass of obfuscation and self-refutation: of giving with one hand and taking back with the other.[73]

This kind of contradiction and vagueness vitiates Jung’s legacy and is a direct consequence of his mixed motivations. It demonstrates that genius depends on dedication to the work, and any failures in this regard will detract from the level of achievement.

Jung’s last recorded words from his death bed seem appropriate: ‘Let’s have a really good red wine tonight.’ The final statement of a man whose personal gifts were astonishingly great – but who consistently and successfully deployed them for his own comfort, convenience and glory.
