# The Evolution of Genius

But how did human societies evolve such that genius – which is at least a-social and perhaps seems anti-social, and often indifferent to reproduction – could manifest itself? On the face of it, genius seems like something that could not happen.

In biological, that is evolutionary, terms – and following-up the insights of Michael A. Woodley; we regard genius as an *altruistic* trait.

Altruistic in this sense means that – on average, in the environment where and when genius evolved – being a genius will tend to reduce the genius’s own personal reproductive success, while genius-caused inventions and other breakthroughs will usually substantially enhance the reproductive success of the group of which the genius is a member. But this genius-caused enhancement of group survival and growth includes unrelated group members, and group members who have not helped the genius – meaning that kin selection and mutual assistance/ reciprocity (the main posited evolutionary causes of altruism) do not seem to apply.

That is, being a genius on average _reduces_ the chances of reproducing successfully, and reduces the probable number of viable children – but the activities of a genius will tend to increase chances of survival of his group, or expand the numbers of people in the group.

Many geniuses have had no known offspring, and statistical studies have indicated a considerably lower-than-average number of children for the geniuses of history.[74] And however imprecise or subjective these studies may be: certainly there is no significant evidence to suggest that geniuses have on average an increased number of offspring – which would be needed to explain the occurrence of genius by ordinary, individual-level selection.

Thus, in terms of survival and reproduction, *being a genius is bad for the genius and good for his group*.

Biological altruism does not (or does not necessarily) correspond with social altruism, or an altruistic personality- i.e. ‘helping people’ – because the genius’s contribution to his community is *via* his work.

Indeed, it is characteristic of the behaviour of a genius that he will protect the conditions necessary for his work, even when this goes against usual and expected socially altruistic behaviour. The genius may therefore be solitary – may indeed be selfish, may not marry or have a family, may not be a good neighbour. But he is selfish not really for his own benefit – not for money or status – but primarily for the work: selfish to enable him better to do (or to do at all) what it is that he does. He is selfish in pursuit of his Destiny, and that Destiny is for the benefit of others.

Some geniuses are nice, many are nasty – but that is not the point. The point is that the genius feels his first (or a very high) responsibility is to do his utmost to create and sustain the best conditions he needs for his work, and to do that work, and communicate that work. He feels his duty is to follow his Destiny. And this motivation comes above the desire to help other people.

(If asked, a genius might truthfully claim to be working for the long-term benefit of his general group – even when this was at the cost of failing to be helpful here and now, in the immediate- and short-term; to his immediate family, friends and colleagues.)

Thus it is quite possible, indeed it is quite normal, for biological altruism at the group level to go with personal selfishness; and for personal un-selfishness to be anti-altruistic, and to damage the reproductive interests of the group. Dean Simonton has found that many geniuses – most obviously Newton, but also many others such as Einstein – were extremely difficult people.[75] By contrast, one can imagine a selfless and kindly person who might assist an individual, out of utter kindness, who was part of a group that was effectively at war with the group of which she was a part. Altruism and being nice: two very different things.

The Paradox of the Endogenous personality is that despite their relative indifference to socio-sexual imperatives; we believe that geniuses have (in evolutionary terms) evolved to serve the group.

The Paradox is that only an inner-orientated personality can be sufficiently independent of the social consensus so as to be able to change the social consensus – when that is needed.

## Group selection of the Endogenous personality.

In effect, and on average, the Endogenous personality sacrifices his own differential reproductive success – including his inclusive fitness, that is, the reproductive success of his closer kin – to favour the reproductive success of the group. By this group, we usually mean the genius’s ethnic or local group.

Australian biologist Frank Salter’s detailed mathematical modelling based on population genetic data has shown that, although there is a social dimension to ethnic identification, the core of ethnic group membership is genetic. Ethnic groups are breeding populations, and a random member of one ethnic group will have more genetically in common with a random co-ethnic than he will with a random member of another ethnic group. As such, there are two ways to pass one one’s genes: directly (through having children) or indirectly (by abetting one’s kin in having children).[76]

This is called inclusive fitness or kin selection – and it means that what looks like altruism at the individual level may be selfishness at the genetic level – indeed, individual altruism is what makes possible genetic selfishness. It works in such a way that the closer the relationship of those who are benefitted, the more powerful is this mechanism – so kin selection is the presumed mechanism that generates the close cooperation and self-sacrifice of social insects such as bees and ants, and most aspects of the ‘clannishness’ of families and closely-genetically-related humans.

A further theoretically possible mechanism for kin selection would be when an individual does not himself reproduce but substantially assists the reproduction of his genetic relatives, as might happen if an uncle without children gave a lot of help to his nieces and nephews, and thereby indirectly promoted the reproduction of the genes he shares with his brother or sister. However, there is no evidence to suggest that geniuses help their genetic relatives any more than non-geniuses, and indeed the genius is likely to do *less* (not more) than average to assist his family – given that he is so devoted to his destined work and problem-solving or otherwise creative activities.

But group selection may be less direct than this; because genius is enhancing the reproductive success of the whole group in a way that typically benefits those who are only distantly related, to the genius – as much or more than the work of a genius benefits close genetic relations (and the family of the genius may also be losing resources by helping to support him).

The ethnic group is merely a highly extended kin network and the genius has no interest in sex or even kindness to his near kin, it would make sense that his evolutionary strategy would favour more distant kin. The group are – in broad terms – an extended family; and the growth of the group may indeed favour the kin of the genius – but this expansion would not necessarily benefit close kin more than remote relations – and the close kin typically have to bear the costs of supporting the genius .

So if we assume that the genius is an evolved adaptation for the good of the group; then what function does the Endogenous personality perform? In a nutshell, *we suggest that the function of the genius is to solve problems which arise from inter-group conflict* – and the benefits a genius provides are typically shared among the whole group among whom he dwells.

Just as the normal situation of individual selection arises from conflict between individuals, so the less common situation of group selection arises from competition between groups – especially when the group is cohesive and the reproductive success of individuals depends upon the survival and expansion of the group.

(Note: There is not, at present, a general and accepted mechanism to explain many or most instances of group selection – although there are some specific suggestions for specific situations. We are therefore arguing that group selection is primarily responsible for evolving the Endogenous personality – but we make no general claims here about how exactly this group selection is operating, at a mechanistic or process level.)

## Group conflict and group selection

Group conflict includes situations in which the individual is dependent on the group, and when the group is under extreme pressure from the ‘environment.’ This is a situation in which only the group *as a group* (and not individuals nor extended families), can survive in a harsh environment, especially in competition with other groups in a similar situation.

The ‘environment’ includes both natural and social environments. Natural environmental pressure could be extreme temperatures (hot or cold), marked seasonality of food availability, or predation from large animals when these problems can only be solved by the group (e.g. the clan or tribe) cooperating and working together, and cannot be solved by individuals or families pursuing their own specific genetic interests. Social environmental pressure could include group versus group conflicts (‘warfare’) driven by factors like competition for land or other finite resources.

In the face of a potentially fatal social problem an individual with the Endogenous personality offers the possibility (but of course there is no _guarantee_) of a novel ‘breakthrough’ answer. For instance, in the face of the prospect of annihilation by the environment, or by another group – a situation in which the group is doomed *unless* there is a breakthrough; perhaps some new technology, some socially-unifying art or form of religion, some way of extracting more resources per unit area, some new weapon or defence. For this kind of *creative solution*, a genius is needed.

If a whole society was composed of genius-type people, it could not function – indeed it would not be a society. But if it altogether lacked Endogenous personalities, then it would only grow very slowly (perhaps by incremental trial and error – which doesn’t always yield an answer to novel problems) and would be at greater risk of being wiped-out by natural forces or group competition.

Thus, we can conceive of roughly two kinds of genius. The scientific-technical genius will increase the chances of a sci-tech breakthrough, or a novel theory that will lead to these. For example, inventions such as the spade, bow and arrow, wheel, plough, railway, radio… these are assumed to be products of sci-tech geniuses; and their value is obvious. This kind of genius may help either group survival or even help to expand the group of which he is part.

By contrast, an artistic, philosophical or religious genius will implicitly aid group cohesion – we term these *cohesion geniuses*. Improved cohesion could therefore be the explanation for the occurrence of artistic genius, or the genius of a storyteller – and also an explanation for religious geniuses who invent new interpretations, beliefs, practices, rituals, stories, scriptures, priesthoods or other forms of institution… that have the consequence of binding-together the group.

Improved cohesion from a religious innovation might then help to enhance growth of the group of religious adherents, perhaps the growth of new forms of political organization, and these might result in the increase of (for example) economic activity or military prowess.

Consider the difference between the Kalahari Bushmen in Africa, and Australian Aborigines. These are broadly similar hunter gatherer societies with a similar level of technology and a similar type of environment. The main social difference is in group size – the Aborigines have significantly larger groups, which means that they cohere better and could assemble larger fighting forces. And the larger Aborigine groups are based around their Totemic religion, which is more fixed and more complex than the fluid, imprecise Animism of the Kalahari Bushmen. Animism is the belief that all living things have souls or spirits and these need to be appeased. Totemism develops this belief, and involves the view that there is one primary source in nature which provides the basis of human life in one’s tribe. The tribe then tends towards worshipping this specific animal – or whatever it may be – to a greater extent than others. Indeed, regular rituals bring the tribe together as they sacrifice the animal in question.[77]

The Aborigine religion both requires and benefits from a more elaborate social structure of authority and learning of the legends – which must be transmitted through the generations by songs and chants. Presumably (of course there is no direct evidence) some (or more than one) Aborigine religious genius created this Totemic social structure – and the group who adopted it was rewarded by improved cohesion, which enabled them to out-grow and displace rival groups[78].

This is conjectural, albeit plausible – it may or may not be historically true; but our point is that somebody at some time made these religious innovations and enabled larger scale and more powerful social cohesion – and this person could be termed a genius (albeit on a local scale) And perhaps many other examples of genius could be regarded as making creative breakthroughs of a cohesion-generating type.

More obvious are the motivational and organizational ‘cohesion geniuses’ who expand the geographical territory of their group – the geniuses of military defence or conquest; the likes of Alexander the Great, Julius Caesar, Admiral Lord Nelson.

We would also expect different populations to produce differing levels of genius, due to differences in local and regional environments. This is something that has been highlighted by Charles Murray in his book, *Human Accomplishment*.[79]

Murray finds that Europeans are behind the overwhelming majority of important scientific and artistic accomplishments between Classical times and 1950. Northeast Asians are in second place, but their contribution is relatively small. This is despite the fact that Richard Lynn has found that Northeast Asians have significantly higher average intelligence than Europeans, outscoring them by around 5 IQ points.[80]

Our proposed answer to the relative lack of genius among Northeast Asians is that they lack the Endogenous personality; presumably from having had a different historical environment than Europeans – an environment which imposed less intense and less sustained group _versus_ group competition, and therefore less powerful _group_ selection for creative innovation (i.e. natural selection for one group to gain an advantage over rival groups). Another possibility is that the environment of Northeast Asia was harsher, leading to stronger selection against Psychoticism and less genetic diversity as survivors would need to be very strongly adapted to the environment, leading to intelligence being bunched towards the mean. Accordingly, the chance occurrence of outlier intelligence combined with moderately high Psychoticism would be less than in Europe.[81] But this is a topic for future research.
