# The Rise and Fall of Genius

## The rise of genius

So far, we have discussed possible general mechanisms for the evolution of genius; and we have argued that genius is the characteristic outcome of the Endogenous personality who is highly self-motivated. But one of the most obvious and striking things about genius, is that there used to be a lot of geniuses – and major geniuses – and now there are very few.

The research in _Human Accomplishment_ by Charles Murray, which is broadly confirmed by others,[@82] indicates that genius in recent centuries has been essentially a phenomenon of the European population, including the diaspora of Europeans to other parts of the world. It seems that in Europe, and only in and around Europe and among its diaspora population, were the conditions necessary for the evolution of the Endogenous personality, who combines both very high general intelligence (g) and the ‘inner’-orientated personality type.

The current evidence suggests that unusually high intelligence _but not the Endogenous personality_ has also evolved in East Asia – indeed the intelligence is probably even higher than in Europe. There are plausible historical scenarios which explain how high intelligence can evolve by multi-generational, individual-level natural selection which favours the reproductive success of the most intelligent members of the population (assisted by sexual selection _via_ assortative mating whereby the most intelligent men and women tend to marry each other, and women in polygamous societies sexually select for the higher status – and so usually more intelligent – men). Gregory Clark has described this (in great detail) for Europe, and Ron Unz (in outline) for China.[@83]

But those aspects of adaptive high Psychoticism which are essential to the Endogenous personality seem only to have evolved in Europe, presumably due to the specific group selection factors. These could include between-group competition in a harsh environment; but one that is not _too_ harsh, such that psychoticism and the chance occurrence of genius is all but eliminated. In addition, it is likely that the Black Death of the fourteenth century, which killed up to half of Europeans but around 80% of the serfs,[@84] provided a significant boost to European intelligence; since the most intelligent classes and groups suffered the lowest mortality rates.

At any rate, in England and later elsewhere in Europe, and from the Middle Ages onwards, there was a tremendous concentration of major, world-historical geniuses, and of major breakthroughs; which came thick and fast; and interacted in a synergistic fashion to trigger first an Agricultural (or Agrarian), then an Industrial Revolution accelerating from about 1700 and taking off about 1800. The result was a tremendous increase in agricultural efficiency and production, and the advent of a new form of social organization based on steam, iron and steel, machines, and transportation – which taken altogether reduced mortality rates, especially child mortality, and enabled rapid and massive population growth.

Our assumption – defended earlier in this book – is that breakthroughs require geniuses, even when the identity of these geniuses is not known or uncertain; as is often the case in agriculture.

Behind many of the breakthroughs of the modern world lies the principle of ‘division of labour’ which was first articulated by the Scottish philosopher Adam Smith (1723-1790). He recognized, described and promoted something that had already begun to happen. Division of labour entailed two things: that the work force should be subdivided to specialize in their functions, and that these specialized functions could be coordinated towards the final result. The result was – potentially – a _massive_ increase in efficiency (output per unit of input) purely resulting from a change of social organization. Smith’s example was a pin factory, where he showed that dividing the task of pin making into specialized functions and then coordinating these workers into a workshop or factory would lead to more than a two-hundred-fold greater number of pins: from a few _dozen_ pins per man per day, to several _thousand_ pins.

This is the essence of that increased productivity which defines the Industrial Revolution – more output for the same amount of input. Indeed, in agriculture the productivity increase went even further, with more production of food for less input of man-hours – meaning that, as well as supporting an increasing population size, much of the previously farming workforce was available to be redeployed into the new industries (indeed, they were more or less forced into the new industries in order to survive).

In agriculture there was enclosure of the large, open fields; effective crop rotations with new winter fodder plants (such as turnips) to sustain larger flocks and herds of animals; the use of manuring and liming to improve crop yields; the invention of selective animal breeding (i.e. accelerated natural selection supervised by men) which yielded more meat, wool, strength etc. from the same number of animals; and the invention of many new tools and machines (often using metal instead of wood) enabling fewer men to do more and a better standard of work.

We assume that each of these breakthroughs was enabled by one or more geniuses; and the combination of these multiple geniuses and breakthroughs was an increase in agricultural efficiency far beyond anything in the history of the world. Some of the contributing geniuses probably included people such as Coke of Norfolk, ‘Turnip’ Townsend (Charles, 2nd Viscount Townshend, 1674-1738), Jethro Tull (1674-1741), Robert Bakewell (1725-95) and many more.[@85]

Increased food production partly enabled the Industrial Revolution, and was also enabled by it – so there were breakthroughs in coal mining (including division of labour and massive coordinated works), transportation (canals, railways, roads), steam power, iron and steel production – also international trade and great improvements in ship-building, communication systems, and the _Pax Britannica_ of military strength (especially naval strength) to enable international trade – which itself had the effect of increasing productivity by specialization and coordination, as was first understood by the English philosopher David Ricardo (1772-1823) in his ‘law of comparative advantage’.

The geniuses who contributed to the Industrial Revolution are extremely numerous and better known than the Agrarians; a mere selection would include the likes of Trevithic and Watt with the steam engine, Bessamer (steel), Crompton (‘Mule’), Hargreaves (Spinning Jenny), engineers such as George Stephenson, Telford, Macadam…

Indeed from the late Middle Ages and through the Renaissance – especially from about 1600 and accelerating – genius was more and more apparent in European sciences, art, music, literature, mathematics, philosophy… almost everywhere. And this continued through into the twentieth century, especially in the sciences – with an especially astonishing constellation of geniuses in physics topped by Einstein.

## The decline of genius

There are a number of reasons to think that intelligence is in decline, and this has become more-and-more evident from the middle of the twentieth century until it is now difficult to deny – since there are very few acknowledged geniuses at all, and some fields without any. This is despite a much larger population, and much better facilities and opportunities.

It is not just the number of geniuses that have declined but their quality – so, for example, in the late 1800s-early 1900s there was Clark Maxwell, Einstein, Rutherford, Heisenberg, Schroedinger, Planck, Bohr, Dirac… and so on and so forth – but a hundred years later there are only a few elderly geniuses left. In biology/ biochemistry, which had its golden era as recently as the middle twentieth century, there are now only a handful of elderly greats left-over from those days – such as American James Watson, the co-discoverer of DNA, and Sidney Brenner, the South African experimental geneticist.

The same picture can be seen even more starkly in classical music – the nineteenth century had Beethoven, Schubert, Schumann, Mendelssohn, Chopin, Debussy, Berlioz, Weber, Verdi, Wagner, Mahler, Brahms… the list just goes on and on. In the early twentieth century there were a few leftovers in Schoenberg, Stravinsky and Richard Strauss and then… nothing.

In English poetry from the fifteenth century right up into the middle twentieth century there were probably always several, sometimes many, genius poets – but since the deaths of Phillip Larkin, John Betjeman and Robert Graves in 1984-5 there are none.

Such impressions are confirmed by systematic studies of exceptional individuals and major innovations, and throughout Europe and the European diaspora – there is a picture of decline – initially decline in _per capita_ rates of genius production, followed by decline in absolute rates; and accompanied by a decline in the magnitude of geniuses.[@86]

Why should this be? If the Endogenous personality is the genius type, and is composed mainly of intelligence and personality, the main explanation is likely to be declining average intelligence, with a downshift in the distribution of geniuses, and (because of the properties of near-normal distribution curves) a very substantial decline in the number of people with very high intelligence.

And indeed that is exactly what we find: a large and rapid decline in general intelligence, insofar as intelligence can be measured objectively (not relatively).

## Decline of intelligence due to the most intelligent having the fewest children

Since general intelligence has a high heritability (approximately 80 per cent), the well-known fact that the most intelligent people (especially the most intelligent women) have the fewest children – in other words the inverse correlation between intelligence and fertility – must tend to reduce average intelligence over the generations.

So, IQ test scores, and proxy measures of intelligence such as educational level, years of education, social class, income; are strongly negatively associated with fertility among women, and to a lesser extent among men. In other words, overall, the more intelligent the woman, the fewer children she will bear.[@87]

This is particularly significant in the modern world where the childhood mortality rate has declined from more than half of children dying before adulthood (even higher among the least intelligent) to about one per cent in Western countries. In other words, nearly all children who are born will now survive to adulthood, and premature mortality rates have become so low as to be almost irrelevant at the population level. Therefore, in recent generations, differences in reproductive success are almost entirely a matter of differences in fertility – the more babies that are born, the greater the reproductive success.

On top of this, since the middle 1960s the fertility among European populations has gone below replacement levels (modern replacement fertility is just above two children per woman – above two to account for premature mortality) – so the age-corrected population of Europeans has been declining for several decades. (This decline in numbers was temporarily masked by an increase in life expectancy – leading to an ‘ageing population’ with a median average age of Europeans being typically around the mid-forties and climbing).

Sub-fertility especially applies to intelligent women; for example, in recent decades more than a third of women college graduates have zero children – and most college graduates are women. The most intelligent and most highly-educated women have extremely few children on average – in Lewis Terman’s follow-up studies of highly intelligent Californians from the early twentieth century, the most intelligent women had only approximately half a child per woman: only about a quarter of the replacement rate.[@88]

The extension of years of formal education and training into the middle and late twenties, resulting in greater and greater delays in initiating families (the average age of a woman having her _first_ child in Britain is now about 30); combined with increased involvement of women in the workforce (a trend that has been strongly encouraged both by radical feminism and by capitalism), seems to have had a particularly lethal effect on reproduction of intelligent women.

This change to extreme sub-fertility among the most intelligent seems to be due to several specific factors working together. One is surely secularism and the decline of religion, which is most evident among the most intelligent.[@89] Even under modern conditions, traditional patriarchal religions often have above replacement fertility[@90] – sometimes very high rates of fertility – _so religion can be an antidote to subfertility_, but it is one which that is seldom used by the most intelligent.

Also important is the rise of contraception, the easy availability of multiple methods of contraception, and its social acceptability – in a context where contraception is more efficiently used by the more intelligent, who would be less impulsive anyway. The legalization and mass usage of abortion is a factor in enabling the decline of birth rates into sub-fertility, although probably not a factor in differential fertility by intelligence.

There are other more general factors, such as a more stable environment – meaning there is no need to have lots of children, so large families will tend to accidental, and underpinned by impulsiveness and thus low intelligence. These adverse trends were probably compounded by a dysgenic accumulation of deleterious mutations caused by the relaxation of mutation filtering from natural selection, mostly caused by the sharp decline in child mortality rates.

In sum, there seems little doubt that the pattern of differential reproduction in relation to intelligence must have had an effect on reducing average intelligence.

## Measuring the decline of intelligence

It is one thing knowing that in principle intelligence must be declining; but the problem is that IQ testing is not suitable for measuring long term trends. An IQ questionnaire is a relative measure: it puts people into rank order by their test results – but it does not give an objective measure of intelligence levels.

In other words, IQ testing is like running races and placing people into first, second, third positions etc., but never using a stopwatch. This makes it impossible to know, over the decades, whether people are running faster, slower or staying the same. What is needed is some kind of objective measure of intelligence: a stopwatch.

This limitation in IQ testing led to the idea by one of this book’s authors (Bruce G. Charlton) of measuring long term trends in intelligence using exactly a stopwatch measure: in other words studying the historical changes in the simple reaction time (sRT) measurement; because reaction times have been measured since the late 1800s, and provide an objective correlate of general intelligence.

Simple reaction times (sRT) typically involve something like pressing a button as rapidly as possible in response to a light coming-on, and measuring the time taken – this procedure usually takes some small fraction of a second: i.e. some few hundreds of milliseconds. Such reaction times are well known to be correlated with ‘g’ (general intelligence). While the correlation with intelligence is not large, sRTs have the great advantage of being objective and quantitative physiological measures – they are more like measuring height or blood pressure than getting people to do an IQ test (which is essentially a form of exam).

Working with Charlton, Michael Woodley discovered an already-published survey of historical reaction time data that demonstrated a striking slowing of sRTs from the time of Francis Galton in the late nineteenth century until the late 20th century. This data carried the strong implication that there had been a rapid and substantial decline in intelligence over the past hundred-plus years – and opened-up a new field of research which Woodley has been actively pursuing ever since.

This initial finding, which Charlton published on his blog, has since been improved, replicated and confirmed by Woodley and his colleagues[@91] who have deployed other convergent methods for indirectly measuring long term intelligence changes.[@92] Using reaction time data, the decline in genotypic IQ is of-the-order of 1.5 IQ points per decade – that is about 15 points, or one standard deviation, in a century; and probably more, over the past two hundred years. [@93] To put this in perspective, 15 points would be approximately the difference in average IQ between a low level security guard (85) and a police constable (100), or between a high school science teacher (115) and a biology professor at an elite university (130).

In other words, in terms of intelligence, the average Englishman from about 1880-1900 would be in roughly the top 15 per cent of the population in 2000 – and the difference would be even larger if we extrapolated back further towards about 1800 when the Industrial Revolution began to initiate massive demographic changes in the British population (although this was a time before reaction time measures existed).

These numbers are not intended to be precise – indeed real precision (in the sense of exact accuracy in averages and measures of scatter around averages) is not available in IQ studies for many reasons to do with the difficulties of truly random and sufficiently large population sampling, lack of a full range of unbiased and objective data; and the fact the IQ points are not on a ‘ratio scale’ but are derived from putting a population sample into rank order on the basis of (usually) one-off testing.

However, the take-home message is that there has been a large and important decline in the average intelligence of Western populations over the past century and more. In every day terms; the academics of the year 2000 were the school teachers of 1900, the school teachers of the year 2000 would have been the factory workers (the average people) of 1900, the office workers and policemen of 2000 were the farm labourers of 1900, while the low level security guards and shop assistants of 2000 were probably in the workhouse, on the streets or dead in 1900.

The substantial long-term unemployed or unemployable, chronically sick or physically/ psychologically disabled, dependent ‘underclass’ of 2000, simply didn’t exist in 1900. And even this estimate is ignoring the expansion of education since 1900, which expanded the middle class occupations and would, in itself, reduce the average intelligence of academics and teachers in 2000 compared to 1900.

## But what about the Flynn effect?

Objective measures show that intelligence has declined rapidly and substantially over the past century or two; but it is also true that the so-called ‘Flynn Effect’ has been evident.

This name refers to the fact that IQ raw scores (i.e. the results on IQ tests, the proportion of correct answers) have been rising throughout the 20th century in Western countries.[@94] So, performance in IQ tests has been increasing at the same time as real, underlying general intelligence has been decreasing.

This can happen because IQ score is a relative, not an absolute, measure of intelligence – and because it is essentially the result of a timed examination involving answering questions. There are likely to be many reasons for increasing IQ scores, indeed any reason for increased exam scores might be contributory – for example improved health, cultural change, educational expansion, socialization of testing procedures, test question and format familiarity, teaching of test strategies, increased use of multiple choice formats (where guessing is encouraged), probably also increased levels of cheating – all may contribute variously to IQ test scores rising even as intelligence declined.

But even the Flynn effect has now plateaued or gone into reverse in a number of countries,[@95] and the rise in scores have been shown to be occurring most on the least g-loaded parts of the tests.[@96] So, general intelligence has been declining substantially and rapidly _even though_ IQ test scores used to be increasing.

Furthermore, it seems likely that while underlying intelligence was much higher in the past, the measurable intellectual performance – for example in examinations, intelligence tests, and in real life situations – of most people was severely damaged by lack of education, harsh physical conditions such as cold and damp, starvation, disease, exhaustion and endemic severe infectious disease, pain and disabilities and so on. Such factors would be expected substantially to reduce (or abolish) many aspects of intellectual performance in difficult tasks by (for example) impairing concentration and motivation.

Imagine doing an IQ test, an examination, or attempting any challenging intellectual activity such as reading a difficult book or performing calculations; while suffering with a fever or chronic pain or gnawed by hunger: imagine suffering fevers, pain, or hunger continuously for most of your life… but this was the normal situation for most of the population in earlier times. No matter what their underlying level of intelligence might be, their performance was significantly impaired for much of the time.

## High-IQ genes versus low-IQ genes

At a genetic level, intelligence may in principle reduce because of a reduction in high intelligence genes in a population and/or as an accumulation of intelligence-damaging mutations in the population.

Differential fertility would lead to a decline in intelligence by a reduction in the proportion of high IQ genes in the population. This happens from a combination of the relatively less intelligent people having on average the most children, and the most intelligent people having very low fertility. Since the most intelligent people are sub-fertile, with less than two offspring per woman, the genes which have made them the most intelligent will decline in each generation – first declining as a proportion of the gene pool, and then declining in absolute prevalence.

For instance, when there is a woman with ultra-high intelligence who has zero children (which is the most usual outcome among ultra-intelligent women), then whatever it was about her genes which made her so intelligent is eliminated from the gene pool: this is the loss of ‘high-IQ genes’.[@97]

But our suggestion of mutation accumulation is that there is an additional mechanism of an accumulation of what could be termed ‘low-IQ genes’. To be clear: these are not genes coding for low intelligence – rather they are damaged genes which pathologically reduce intelligence. So, as well as there being a decline in intelligence from the reduced proportion of ‘high-IQ’ genes, there is also an increase in the proportion of ‘low IQ genes’ in the population.

High IQ genes have (presumably) been selected for in the past because they increased intelligence, and thereby (under ancestral – especially Medieval – conditions) increased reproductive success.

But low IQ genes are not, in general, a product of natural selection: rather they are spontaneously occurring deleterious mutations, which happen with every generation due to any cause of genetic damage (e.g. electromagnetic radiation, chemical damage), or errors in replication.

These mutations will, if not eliminated, accumulate generation upon generation. Therefore when they have accumulated, the low-IQ genes were not ‘selected for’; rather it was a matter of _lack of_ selection, relaxation of natural selection. ‘Low IQ gene’ therefore usually means something like a genetic mutation that – in potentially a wide range of ways, by impairing almost any aspect of brain structure, organization or functioning – actively damages brain processing speed and efficiency, hence reducing general intelligence.

In technical terms, the selection mechanism for eliminating these spontaneously accumulating low IQ genes is mutation-selection balance. The idea is that mutations spontaneously occur and need selectively to be eliminated. In other words, by some means, those organisms which have damaging mutations must (on average) fail to reproduce – must indeed _be prevented from reproducing_ – so they will not hand-on the mutations to the next generation, and contaminate the gene pool with mutations.

Conversely, only a small proportion of the population – i.e. those with good genes – are allowed (by the selective environment) to reproduce; and typically this minority will provide nearly all of the next generation.

Since there are new mutations each generation, as well as the possibility of some inherited from parents, the process needs to be perfect over the long term, otherwise the accumulation of damaging mutations will eventually prevent reproduction and damage survival to cause extinction. The term for such extinction is _mutational meltdown_ – and this has been observed to occur in some lower organisms, especially when mutations are accumulating and the population is reducing. This probably happens in some inbred captive populations such as in zoos, as well as in modern human society.

The term mutation-selection balance refers to the fact that the occurrence of mutations must be balanced by the elimination of mutations: natural selection (including sexual selection – mate choice) must be powerful enough to sieve-out all the deleterious mutations. If natural selection is not strong enough to do this, then mutations will accumulate, brain function will be damaged, and intelligence will decline.

Each spontaneous mutation has about a fifty-fifty chance of damaging brain function, because the brain depends on a very high proportion of genes to develop normally and make its structural components, its proteins, enzymes, hormones, neurotransmitters and so on. Thus the brain is a large ‘mutational target’ (as Geoffrey Miller has termed it) – and will usually show up, in a quantitative fashion, the amount of mutational damage a person has. In other words, high intelligence requires ‘Good Genes’ – where good genes means a genome low in mutations; conversely a high mutational load will cause low intelligence.

Before the Industrial Revolution, individuals with a higher mutational load, which means a higher load of low-IQ genes (and therefore lower intelligence) had lower-than-average reproductive success due to very high (indeed, probably near total) childhood mortality rates. But since the child mortality rates fell from more than half to about one per cent in most of Europe, almost all babies that are born have survived to adulthood, and most of them have reproduced. Therefore, we must assume that there have by now been several generations – in England at least eight generations – of mutation accumulation. And we must also assume that this has had a significant effect in reducing intelligence.

This produces what is truly a ‘dysgenic’ effect on intelligence, since it is not evolved, not adaptive, not a new ability – but instead a lowering of intelligence due to a pathological process; a destruction of adaptive human intelligence caused by an accumulation of damage.

And although intelligence decline is a sensitive measure of mutation accumulation – it is not the only consequence. Many other human adaptations would be destroyed by mutation accumulation – including evolved human personality types. As well as pulling down human intelligence; mutation accumulation would be expected to destroy the Endogenous personality, to impair human creativity – and would be a further nail in the coffin of genius.

## Decline of intelligence due to mutation accumulation

So, the decline of intelligence that has now been measured using reaction times and confirmed with other methods, has been too fast, and gone too far, fully to be accounted for by the mechanism of differences in fertility between most and least intelligent.

To re-emphasize; we have no doubt that this mechanism of differential fertility has had an effect in reducing intelligence over the past two hundred years, but there must be other additional explanations for so great and rapid a decline in intelligence – a decline (we argue) that has been sufficient to all-but eliminate world class geniuses from the European population, and hence the world.

We therefore suggest that the main additional mechanism to reduce intelligence may plausibly be the generation-by-generation accumulation of deleterious genetic mutations; as a result of the near-elimination of historically high child mortality rates which used-to clear mutations from the gene pool with each generation.[@98]

But after the Industrial Revolution got going, mortality rates declined for the least intelligent along with everyone else; so that even the poorest families usually raised several-to-many children, then there was a _double-whammy_ dysgenic effect: a reduced proportion of high IQ genes with each generation (due to progressively lowering fertility among the higher IQ) and also an increasing accumulation of low IQ genes (intelligence-damaging deleterious mutations) with each generation.

In sum, since the Industrial Revolution, individuals with the greatest mutational load (IQ-harmful genes) have been initially been above-replacement fertile (having on average more than 2 surviving children per woman, for the first time in history perhaps), and also differentially more fertile than those with the least mutational load. And compared with 150-200 years ago, there is now a lower proportion (and a lowering absolute amount) of IQ-enhancing genes in the gene pool of England, plus a higher proportion and accumulation of deleterious IQ-damaging mutations. And this double-whammy effect is, we think, why average general intelligence has declined so rapidly and so much in England over the past couple of centuries.

## Historical trends in the prevalence of genius

So, the first effect of the ‘perfect storm’ of English geniuses (also probably seen, although not yet documented, in several other European nations such as France and Germany) was to expand the population and thereby increase the number of English geniuses; but as the generations went by, the adverse selection factors and mutation accumulation would have ‘sabotaged’ the expansion of geniuses by reducing the average intelligence in the population – firstly the proportion, and then the actual number, of people of very high intelligence, so that the number of new geniuses occurring dwindled into again being extremely rare and ‘one off’.

As a consequence, it has been documented by Woodley and others that the number of ‘breakthrough’ macro-inventions – major inventions that really alter how we live – has decreased markedly since the Victorian Era, though there are still many micro-inventions, which are merely tinkering with macro-inventions.[@99]

For example, a macro-innovation like the computer was invented by geniuses (such as Babbage, Turing and von Neumann) up to the middle twentieth century; and the multiple improvements in miniaturization, processing speed and memory etc. – which have made the computer so widely useful – are classified as micro-innovations, and were made by a multitude of people and organizations, often employing ‘trial and error’ type methods.

So, micro-innovations are extremely important, and make a big difference, and take some decades to emerge –the fact is that micro-innovations are not so difficult as macro-innovations. In particular micro-innovations do not require such exceptionally creative people as macro-innovations – but instead can emerge from knowledge accumulation, high-normal levels of cleverness, communication, and routine ‘research and development’.

The importance of genius in human history – and specifically in modern society – is that we argue that it was the uniquely high number and concentration of geniuses in the European population that triggered and sustained the Industrial Revolution. Genius-generated macro-innovations provided the foundation for amplification by numerous micro-innovations; and the combination supported an expansion in world population from about one to seven billion, and still growing.

As intelligence declines, the foundations for this socio-economic system will be removed. The breakthrough-upon-breakthrough needed to provide and sustain growth will presumably be the first to dry up. Then there will be a period of plateau when people can continue to exploit and marginally-improve upon the successes of the past – some decades as micro-innovations are developed. (These stages are probably already behind us.)

But as intelligence continues to decline, then growth in productivity will reverse into decline and inefficiency, as the ability of people to sustain, repair, even to maintain, the highly technical, specialized and coordinated world civilization will be lost, just as occurred with the fall of Western Roman civilization; when agricultural and industrial production and trade all collapsed, the standard of living and population plummeted, and general technical and organizational levels took more than a millennium to recover.

When the supply of major geniuses becomes inadequate, or dries-up altogether, then the past two to three centuries of world productivity growth – which depended on a continual stream of major discoveries – one innovation making possible another, one repairing the problems generated by another, and all of them interacting to enable further innovation… all this will come to an end. And since modernity (the socio-economic system since the Industrial Revolution) depends on growth – specifically growth in capability and efficiency/ productivity – then modernity will first halt, then reverse.

Arguably this reversal has already happened in The West, and we are now living off capital – well embarked on a downslope of reduced societal efficiency which affects all nations (because the innovations and breakthroughs created by geniuses of European origin have usually spread to the rest of the world).

So, we believe that the end of the ‘age of genius’ entails the end of modernity – the end of the type of society that has dominated and spread across the world since the Agricultural and Industrial Revolutions; whether the cause is that we have run out of geniuses, or because (as some people argue) we have merely run out of major things for geniuses to discover. Either way, the consequences are the same: the collapse of modernity, which absolutely depends on a steady supply of geniuses and breakthroughs – and reversion to pre-Industrial Revolution conditions, of one sort or another.
