# The neglect and suppression of genius

## Genius and the educational system

The Genius Triad is intelligence, intuitive creativity and long-term self-motivation – all focused on the same domain. Psychologically the triad could be termed Questing Creative Intelligence; and QCI will be found not only among potential geniuses of the major type, but also with lower strength among small-scale geniuses, more local or partial geniuses; who, although capable of far less than the likes of Rutherford, George Stephenson or Alan Turing; nonetheless will work for, and tend to make, original breakthroughs. It is up to other people whether these breakthroughs are noticed, understood and used; or (as so often happens at present) ignored, vilified and suppressed.

With the decline in average intelligence, and the resulting decline of genius, society becomes ever more short-term oriented and politically less stable as these factors have been shown to be underpinned by national intelligence. Richard Lynn and Finnish political scientist Tatu Vanhanen (1929-2015), for example, have shown that numerous measures of civilization – education level, sanitation, democracy (and so smooth transfers of power), political stability, and lack of crime and corruption – are all moderately to strongly predicted by national IQ.[100] And they have shown that these national IQs are highly reliable as they strongly correlate with national measures of proxies for IQ, such as international student assessments.

In a society of declining intelligence, we would expect: rising crime and corruption; decreasing civic participation and lower voter turn-out; higher rates of illegitimacy; poorer health and greater obesity, an increased interest in the instinctive, especially sex; greater political instability and decline in democracy; higher levels of social conflict; higher levels of selfishness and so a decline in any welfare state; a growing unemployable underclass; falling educational standards; and a lack of intellectualism and thus decreasing interest in education as a good in itself. We would also expect more and more little things to go wrong that we didn’t used to notice: buses running out of petrol, trains delayed, aeroplanes landing badly, roads not being repaired, people arriving late and thinking it’s perfectly okay; several large and lots of little lies . . .

In addition, the broader modern system – especially of extended formal education (stretching ever further into adult life), exam results and continuous assessments, required subjects and courses; the supposed ‘meritocracy’ – suppresses the influence of genius, since the Endogenous personality is seeking, ever more strongly with age, to follow his inner drives, his Destiny, and all the paraphernalia of normal, standard requirements stands in his path. While others need sticks and carrots, and are grateful for encouragement, discipline and direction; the Endogenous personality is driven from within and (beyond a basic minimum) he neither needs nor appreciates these things – at best they slow him down, at worst they thwart and exclude him. The Endogenous personality requires mainly to be allowed to do what he intrinsically and spontaneously wants to do – but in modern society he is more likely to be prevented.

Creative people always have difficult personalities; and conversely nice people with conscientious, obedient reliable personalities are not creative. This means that institutions, employers and patrons must tolerate the difficulties of Endogenous personalities, if they want those things done that only geniuses can do. Most of the time, potential geniuses are a nuisance – but there are times when such people are essential.

However, in order to do these things geniuses, have to find themselves a job or a university place or a patron. In a less meritocratic society, this might be via family connections or informally demonstrating one’s genius. In other words, the difficult short term decision to appoint, tolerate, perhaps even reward an asocial Endogenous personality instead of a conscientious and popular Head Girl type might be made by an individual who knew the nature and potential of the Endogenous personality (perhaps because he was himself an Endogenous personality).

But, nowadays, such decisions are usually made by committee vote, by officials and bureaucrats who are themselves usually the opposite of geniuses; and done according to guidelines and protocols – ‘standard procedures’ and an attitude of risk-minimization will almost invariably tend to exclude geniuses, who are nearly always lop-sided with weaknesses as well as strengths, and each a one-off in terms of aptitude.

The Endogenous personality combines high intelligence with the ‘inner’ personality; and it used to be fairly normal for Endogenous personalities to gain admittance to the most elite institutions. However, nowadays, it is clear that college admission criteria are much less likely to select for intelligence than in the past. In other words, attendance at the most selective institutions is no longer a matter of being of the highest intelligence. Partly this is because of the changing nature of educational evaluations – the best reports and grades at school or top performance in exams are no longer so ‘g-loaded’ that is, they are less correlated with general intelligence than they used to be (some of this may be due to the IQ test score inflation which is termed ‘the Flynn Effect’).

But it seems certain that ‘elite’ modern institutions are not evaluating and selecting primarily on the basis of intelligence – since they do not use intelligence tests, high intelligence is only selected-for insofar as it correlates with the educational, personal and other assessments which are used for selection – and the correlation between these and intelligence is not close (around 0.5 for high school achievement), and much less close than it used to be.

Nor are the elite modern institutions selecting for personality qualities of independent and inner motivations and evaluations that are an intrinsic part of the Endogenous personality – quite the opposite, in fact; since there are multiple preferences and quotas in place which net exclude European-descended men (that group with by far the highest proportion of Endogenous personalities – i.e. having the ultra-high intelligence and creative personality type). This can be seen in explicit group preference policies and campaigns enforced by government (and the mass media), and informal (covert) preferences – leading to ratios and compositions at elite institution (especially obvious in STEM subjects: i.e. Science, Technology, Engineering, Medicine) that demonstrate grossly lower proportions of European-descended men than would result from selecting for the Endogenous personality type.

Indeed modern institutions are not even trying to select primarily by intelligence – the reality of which they often deny; but instead are implicitly – by the nature of their evaluations – and also by explicitly-stated policies – selecting on other grounds, especially for the ‘Head Girl’ personality – the conscientious, empathic, socially integrated all-rounders. Modern society is, of course, run by Head Girls, of both sexes (plus a smattering of charming or charismatic psychopaths), hence there is no assigned place for the creative genius. Modern colleges aim at recruiting Head Girls, so do universities, so does science, so do the arts, so does the mass media, so does the legal profession, so does medicine, so does the military. And in doing so, except insofar as they make errors; they filter-out and exclude even the possibility of creative genius.[101]

If a creative genius does somehow happen to get-through, by error or accident – that is, someone who can recognize the Endogenous personality and may be expected to favour it – then he will not in practice be allowed to select more of his type; because of the way that all significant decisions are taken by committees (dominated by Head Girl types) and controlled by checklists, guidelines and protocols. These will have been designed, and are enforced, by Head Girl types with the aim of excluding those who do not conform to what is ‘normally’ required (thereby excluding those who are better than normal, along with those who are worse than normal).

As a result of the above trends, the most intelligent and the most creative people are nowadays dispersed among variously ranked institutions (and no-institutions-at-all); and typically have sub-optimal – sometimes frankly bad – academic and employment records. The Endogenous personalities are very seldom to be found in the most prestigious, best-funded, or fashionable subjects (unless they were the original founders of the field, or perhaps at a low level or in a marginal capacity) – since a genius is stubbornly self-motivated, and will work only where his destiny leads him (and he may refuse or neglect work that interferes with his destiny). The fields in which genius is questing are as various as the people with genius; and will often strike other people as futile or absurd; nonetheless, ‘eccentricity’ is intrinsic to the necessary autonomy of genius.

## Genius and societal self-interest

The reason for society to tolerate and sustain geniuses is not that geniuses deserve more concern than other kinds of people – the bottom-line reason is societal self-interest.

Geniuses are ‘for’ the good of the human group; they are people with a special gift for solving specially-difficult problems; and all human societies are confronted – sooner or later and usually sooner – by the kinds of problems that can only be solved by geniuses; lacking-which, the problems are simply not solved. British mathematician Alan Turing’s (1912-1954) cracking of the Enigma code – portrayed in the 2014 film The Imitation Game is a case in point. This intensely difficult man had to struggle against Head Girl types to get a job for the government and then to build his code-cracking machine. But if there had been no Turing, the War would have lasted significantly longer, with terrible consequences.[102]

To reiterate, geniuses are people who combine an especially high intellectual ability with a spontaneous tendency to focus on some abstract (by ‘abstract’ we mean ‘not-social’) problem, and the inner motivation to maintain this focus, to quest for an answer, for relatively long periods of time. However, there are only two ways that they can realistically find the space to pursue their genius: a patron or, in some cases, a well-funded university.

Indeed, if the genius can become an academic he is confronted with further problems. Once upon a time, he could do occasional teaching and then devote himself to his research, publishing if he discovered anything. Now, there is constant pressure to publish, publish in certain journals, attend conferences (Hellish social events for geniuses), and obtain research grants. This would drive many geniuses out of academia, leaving it dominated by the Head Girls.

To read of such difficult, annoying, disruptive geniuses as mathematical physicist Paul Dirac (1902-1984; who almost never spoke)[103] or the philosopher Ludwig Wittgenstein (1889-1951; who refused to socialize or even eat with colleagues, or do administration; and taught only the people he wanted to teach and in exactly the way he wanted to teach them),[104] and then to realize that these were Professors at the world-leading University of Cambridge – is to recognize that such characters would nowadays get nowhere near a Cambridge chair or any other chair (not least because actual ability to perform at a really high level in one’s subject or function, is no longer regarded as of primary importance in modern British universities, or indeed anywhere else in Britain).

Where instead do such men find themselves? The answer is not known for sure – but anecdotal information and our personal knowledge suggests that they are scattered in multiple and various marginal and low status circumstances, where their potentially vital work is assiduously ignored, mocked or attacked – and this endemic and chronic hostility sooner-or-later tends to have a knock-on, deleterious, distorting effect on their attitudes and output; inducing a bitterness, pride, aggressive irritability, a siege mentality, despair and inertia – or some other wholly-understandable but profoundly unhelpful and achievement-destructive frame of mind.

Meanwhile, compliant, careerist, sociable mediocrity is zealously enforced by the ruling Head Girl types; whose primary, often sole, concern is their own social micro-environment. And as average intelligence has declined, two things have happened that have had a major impact on the university.

Firstly, the ideal of the pursuit of truth has been replaced by the pursuit of an ideology. And secondly, the idea that education is a good in itself – an intellectual idea, requiring honesty, personal dedication, and long term thinking in terms of the future and nature of society – has disappeared; to be replaced by the view that it is a means to an end, a way of getting a certificate, making money, having a ‘party’ lifestyle – things in which the potential genius is not really interested (and should not become interested).

So colleges and universities – which used to be a haven for geniuses – have instead become a mixture of ideological churches; holiday camps; schools of dissipation and irresponsibility; ‘learning shops’ run by managers, accountants and public relations professionals; and research factories generating ‘evidence’ as required by whomsoever has money enough to fund them.

Thus in Britain, and in all the other European and European diaspora nations (the USA, Canada, Australia etc.); we see the same picture of a society with a high concentration of effective geniuses that flipped, quite suddenly – and in the space of a generation or two – into a society which is in practice, and almost universally, actively anti-genius: a society selecting against genius, excluding of genius, persecuting of genius.

## Fake creativity

Although the picture is one of an extraordinarily rapid decline in the prevalence of geniuses, the trend has been confused and clouded by the simple expedient of re-labelling and denial.

By re-labelling, some non-creative nonentity (maybe someone of high career status, maybe of high but un-creative ability, maybe a charming character, maybe just a novelty-merchant) is simply stated to be a genius, repeatedly talked about as a genius – probably given awards and medals for being a genius – and the concept of genius is thereby blurred, relativized and even further discredited.

By denial we mean the common notion among sophisticated modern people that ‘geniuses’ are no different from anyone else – the denial that there is indeed such a thing as a genius – that the whole thing is a matter of luck or labelling, or a cult of personality, or romanticism – or part of an hierarchical (and probably patriarchal) conspiracy. By the end of this deconstruction and subversion, the disappearance of genius has been disguised by denying that there ever was genius, and the whole thing relativized into a matter of professional eminence, or even just fame or notoriety – so the latest ‘shocking’ novelist is actually, basically, the same as Shakespeare; the latest art gallery ‘installation’ doing the same thing as a Rembrandt portrait or a Rodin sculpture.

This can be seen most obviously in fields where, by the evaluative standards of a century ago, there are no living geniuses at all. For example classical music, fine art, and poetry (in English).

Worse still, ‘originality’ – rather than consequence – has become the test of genius. The fact that something is ‘original’ – meaning novel, makes it praise-worthy. In fact, originality has now become indistinguishable from mere changes of fashion.

In previous eras, there was not a special status given to novelty as an aspect of high quality work – but since about 1800 in the West there has been: greatness is supposedly mostly a matter of being innovative. Yet while great geniuses may innovate this is not the rule, for instance Gluck and J.C. Bach were greater innovators, but much lesser composers than, J.S. Bach and Mozart; Constable and Gainsborough were less original, but higher quality, painters than Francis Bacon or Lucien Freud.

Therefore we currently have an incentive system in place to generate fake creativity: an incentive system in which there are un-creative people who dishonestly strive to be regarded as original because they want to appropriate the label of creative and usurp the title of ‘genius’. In sum, under modernity creativity has been reduced to novelty – and novelty can be simulated.

It is trivially easy for clever and well-trained people to generate mere novelty, so there is an excess of it (we call it ‘fashion’). Therefore the discriminative test applied to novelties is whether they are approved by the social systems that allocate high status. When novelty is socially approved, then the person who generated it gets to be called creative – maybe even a creative genius.

Thus: Novelty of outcome + Social Approval of that outcome = Fake creativity

And fake creativity is an attribute bestowed upon an outcome or person; bestowed by the social systems for generating status – in other words the mass media (primarily), politics, civil administration, the legal system, education... in a nutshell the Leftist Establishment.

We regard it as quite obvious and undeniable that the Establishment is now ‘Leftist’ as evidenced by dominance of those with this perspective in academia, among senior churchmen, in the media, and in all mainstream political parties – all of which promote some degree of Political Correctness. The radicals of the 1960s, and their followers, are the honour-loaded Establishment of today. The British philosopher Sean Gabb has documented how, since the 1960s, the Left has displaced the traditional ‘conservative’ Establishment, taking over almost all of organs on the British State, including the police and legal system.[105] The dominance of Leftism in academia has been documented in numerous studies.[106]

So, as would be expected, political correctness has captured creativity – and replaced real creativity with a fake creativity which is controlled by the arbiters of modernity: that is, mostly the mass media. So modern ‘creatives’ are celebrated for their subversion of (or exposure of the supposed hypocrisy of) traditional, bourgeois and religious values; and rewarded for their celebrations of equality, pacifism, rebellion, feminism, sexual experimentation, antiracism, multiculturalism, and the rest of it...

This matter of being able to define/ bestow the accolade of creativity is of extreme importance to the modern intellectual establishment – indeed, fake creativity stands close to the heart of the ideological project of the modern (Leftist) elite – because the Left works mainly via manipulations of esteem, including self-esteem. Its enemies are portrayed as immoral (especially ‘selfish,’ judgemental or ‘racist’ and thus associated with the Nazis and their horrors) and of low intelligence, knuckle-dragging crudity, retardation and/ or lunacy.

Thus to claim to be a ‘creative’ person has been changed from being the mere observation of a psychological fact; to an arrogant claim of deserving high social status for having achieved something which is approved by social arbiters.
