# The War on Genius

When we observe past societies, and how they were able to sustain geniuses and make us aware of the work of geniuses; the question arises: How was it that such simple and unselfconscious societies could spontaneously recognize and respond to something as complex and unpredictable and unique as a genius – when our much more prosperous and complex society cannot?

The reason is just that most human societies of the past, and certainly those societies where genius most thrived, were serious; they recognized that life is a serious business, that there is a reason for it all, a purpose to it all, and (in those societies where genius was most prevalent) that each person had a part to play – by contrast, at least in mainstream public discourse, modern Western society does not acknowledge any of this.

Charles Murray, in *Human Accomplishment*, suggested what we believe to be one correct answer: that for people in the past, the human condition was (in one way or another) eternally significant. Not only that, but life was perceived to be fragile, existential threats such as conquest or collapse were close at hand; and the people responsible for rulership knew a certain ‘type’ of personality had been able to solve major and unprecedented problems in the past.

But modern society has all-but lost this sense of the seriousness of life. We agree with Murray that this is substantially a consequence of the process of secularization, a matter of the loss of religion – since the most genius-conducive religions create a perspective extending beyond our mortal life and immediate sensory and emotional experiences. In public discourse, religion has been replaced by various secular, this-worldly socio-political ideologies. But all modern Western countries now share a triumphant, generically-Leftist ideology (extremely Leftist by world historical standards) that embraces all mainstream politics, administration, mass media and leadership. This underpins all the powerful political parties including those which are self-identified as Conservative, Republican, Nationalist, Libertarian and religious; and including leadership of all large organizations, institutions, and corporations – whatever their titles or self-definitions.

The modern ideology is compounded of human rights, equality, individuality, minimization of suffering and maximization of self-respect, diversity, inclusion and a strong emphasis on non-traditional sexual self-expression and identity. But the point is not so much these positive doctrines as the negative ones: this-life is all there is, and there is no meaning to life beyond the happiness or misery experienced; there is no objectivity to morality, humans are existentially alone and communication is uncertain and mostly a matter of self-deception. In sum, the modern ideology is secular and nihilistic, and modern people are short-termist, pleasure-orientated, and alienated.

One reason for the decline of religion is ‘luxury’ – that is the high levels of comfort and convenience in modern life, and the detachment from the natural world and immediate threats to survival. With the Industrial Revolution, the reduction of child and young adult mortality, the de facto elimination of starvation and mass lethal epidemics, the provision of near universal shelter and warmth etc.; plus actual and the expectation of continually-rising standards of living and ever-more-abundant provision of pleasures and entertainments – from all these factors and others the causes of our acute sufferings and fears have very much been taken away and, on a daily basis, we are so insulated that there seems to be no pressing need to believe that life has eternal significance.

Religiousness seems to be motivated and enforced by direct environmental stress. For instance, it reduces stress at the prospect of mortality by making us believe that our life is eternally significant. This is why perceived religious experiences tend to occur at times of danger or to people prone to stress.[107] Elimination of directly acting stresses tends to weaken or altogether abolish religion. In contrast, the abstract, free-floating, impossible-to-locate ‘angst’ of modern life clearly does not lead to religiousness; but rather to despair.

It seems paradoxical to moderns (who usually believe, or at least assert, that the existence of suffering refutes the reality of God); but the harder life is the more strongly religious people tend to be (for instance, the most recent significant Christian revival in Britain occurred during the Second World War); and the more comfortable and convenient life becomes, the less people seem to need religion, or to get immediate personal satisfaction from church membership and participation.

Of course people still feel gnawing anxiety, depression and despair. But these do not trigger religiousness, being increasingly dealt with by 24/7 distraction provided by the mass media, interpersonal communication and quick transportation; any dysphoria (mild depression or otherwise unpleasant feelings) is dealt with by mass medication with tranquillizers and emotion-numbing ‘antidepressants’, ‘antipsychotics’ or ‘mood stabilizers’ (these words are placed in ‘scare quotes’ because they are all marketing terms with negligible scientific or clinical rationale).

Modern Man can, if he wishes, ignore his mortality, not think about it – so distant is it from everyday life; so many and so thick are the insulating layers between himself and the real environment of food, clothing, shelter and warmth; invaders, predators and parasites. He can live absorbed in a world of drugged distraction. And this is, pretty much, the totality of the modern vision of life.

As such, the Endogenous personality, or potential genius, is perceived as a problem for modernity because the genius is only appreciated, only makes people happy, when there is an acknowledged crisis. And when there is no obvious crisis or, if there is, it is so far in the future that most of us lack the future-orientation (in other words, the intelligence) to worry about it or even believe in it; or when we can simply be persuaded (by the mass media) to deny or ignore the crisis, or re-label crisis as progress . . . then the genius becomes just an annoying and apparently unproductive person: a social irritant rather than a potential societal saviour.

So, modern society is in practice indifferent or hostile to genius and the products of genius; since we are complacent, trivial and evasive. For us, problems are merely part of the world of sensation and entertainment – continually defined then re-defined; and genius is just one of many millions of things to be taken-up, contemplated briefly, then impatiently set aside in the unending quest for novel stimulations.

Also, modern institutions are almost always controlled by managers; and managers do not participate directly with the primary function of organizations (e.g. managers of research do not do research, managers of hospitals do not provide health care, managers of widget factories do not carve the widgets) – therefore for the manager (qua manager) ‘the bottom line’, the effective ‘reality’ is ultimately the perception of others. This is why, as management takeover has become more complete in The West; management of perceptions, impressions, opinions etc. has come to dominate organizations. For management, ‘truth’ is what people currently think is true, and if what-people-think can be shaped to suit expediency– then so can ‘truth’.

Therefore, it seems that modern society is indifferent/ hostile to genius for the simple reason that as – a human group – we perceive no real and urgent sense of group self-interest. We cannot really believe in real-problems and the real-need for real-solutions – we deny that there is a price to pay for survival, and that genius is one of these prices.

And insofar as modern society is aware of geniuses having provided solutions to real and vital societal problems, these answers are typically vehemently rejected. We don’t acknowledge tough problems demanding tough solutions – we instead demand easy answers. Indeed, we really don’t want answers – because we pretend things are already solved, or that solutions just happen, naturally, as part of the nature of things; or that what we currently happen-to want-to do will also (miraculously!) provide exactly the answers we most need.

This is significant because we believe genius to be group selected. Modern man seemingly cannot any longer believe that human group cohesion is vital for continued existence and prospering – we see ourselves as in essence atomistic, autonomous individuals and not as integral members of a group. All this can be seen in the often-remarked loss of social cohesion at the level of workplaces, neighbourhoods, clubs, hobbies, churches, schools, colleges, crafts and professions – what is termed the decline in Civil Society – all these groups have been weakened, subverted or even destroyed by The State to which most people now look to provide their wants. Since civic involvement has been shown to be positively associated with intelligence, we should not be surprised to observe its decline.[108]

As already discussed, it is not just intelligence which is declining but also other adaptations such as the General Factor of Personality: so we are on average less pro-social, more anti-social and asocial. And fertility is inversely associated with education, as well as with intelligence – expanding education to include ever wider sectors of the population for ever longer periods of life has therefore (independently) imposed further damage on the fertility of the most intelligent on top of long term intelligence related trends.[109] Educational success is predicted by the GFP. So, we are becoming less Agreeable, less Conscientious, less group-oriented in multiple ways. Indeed, mutation accumulation would be expected to damage all types of evolved adaptation; perhaps first and especially social adaptations, which tend to be most sensitive to brain pathologies (psychiatric and neurological diseases show-up in social deficits and pathologies more sensitively than in other aspects of functionality).

In sum, under modern conditions individual selection subverts group selection, individual selfishness subverts group selfishness – and each person increasingly aspires to be a ‘free rider’: getting more than he gives, living at the expense of the group as chronically unemployed, chronically ‘sick’, long-term retired; living life as a continual party, travelogue or holiday.

Short-term selfishness replaces long-term groupishness – and an utterly ineffectual, feel-good emotion of universal or ‘global’ benevolence has replaced the tough choices, personal involvement, hard work and specific duties imposed by long-term loyalty to defined groups.

## The problem of evil geniuses

Although we argue for the importance of creativity in human affairs, and therefore of the importance of the creatives who do the primary work of creativity, it should not be forgotten that creativity is not only a positive human value in itself, but is also a means to an end; and that end may be socially good or bad, creative and cohesive, or socially subversive and destructive. As society has lost a sense of its eternal significance, creative types – indeed geniuses – can be found in the pursuit of things that a ‘traditional society’ would regard as ‘evil.’

Modern society has indeed become more and more ‘evil’ – which is to say (providing here a brief definition of evil) organized in pursuit of destruction of The Good in the traditional sense of the word – the Good being (roughly) the transcendental values of Truth, Beauty and Virtue, underpinned by a sense of unity and the eternal.

Thus modern leadership in many areas of life is engaged, both passively by neglect and actively by policy, in destruction of truth, beauty and virtue – indeed, frequently in inversion of values; so that modern ideas of TB&V are often the opposite of traditional: for instance, ‘subversive’ is now a term of praise. That is to say, modern leadership embodies and enforces a morality which takes reality and turns it upside-down – so that good becomes evil and vice versa. This Nietzschean project of ‘the transvaluation of all values’ is far advanced, albeit incompletely realized, and indeed it cannot ever be fully realized – nonetheless, ‘progress’ towards its realization continues incrementally and cumulatively. In such a context, it is unsurprising that most existent creativity is harnessed in pursuit of this ‘evil’. After all, genius is a form of power, and in an evil world power is likely to be used for evil purposes.

In the first place, much of this distinctively modern form of evil by inversion is a product of highly creative persons, such as Nietzsche himself, and lesser emulators who not only extrapolated his ideas, but creatively enhanced them. Examples include many of the modernist artistic subversives of early 20th century art. We have already mentioned Picasso, Schoenburg and James Joyce – who seem to have inflicted net harm; and there are many equally influential partial-geniuses such as Duchamp, John Cage, Ezra Pound, William Burroughs, and Samuel Beckett – men whose considerable creative gifts were harnessed to what was sometimes actively intended to be, and sometimes merely turned-out to be, subversive, inversional and destructive agendas.

In essence, and in opposition to the past ‘cohesion geniuses’ of religion, philosophy, literature, music, and art that we mentioned earlier; modern ‘evil geniuses’ have used their creativity to undermine rather than strengthen social cohesion; to argue or demonstrate that there is no such thing as truth, or that the false is true; to assert that life has no meaning, to assert that forms of immorality should be praised as virtuous, and to reject beauty in favour of originality or even to try to promote ugliness as beauty.

In other words, they used their genius to reverse the values of the past and promote a dark, nihilistic and despairing Void of a life.

Secondly, due to the fact of creativity being part of the personality type of ‘Psychoticism’ – creatives may tend to be more-than-usually vulnerable to the consequences of impulsivity and less restrained by social ethics: they are lone wolves with a potentially predatory attitude which is relatively easily corrupted by short-term and selfish incentives, as we have seen of Jung.

Most often this can be seen in sexual and monetary exploitativeness, shirking, lying, cheating, seducing and sponging of the stereotypical ‘Bohemian’ lifestyle; that once defined became widely emulated (for instance by the Beats of the 1950s, or the Hippies of the sixties) – with predictably self-destructive effect; for instance in the lifestyles, anti-morality and premature deaths of writers such as Arthur Rimbaud (1854-1891),[110] Oscar Wilde (1854-1900)[111], Jack Kerouac (1922-1969) and the numerous talented casualties of the rock and pop music scene.[112]

Thirdly, creatives – who might in principle exercise their creativity on anything – will find, but may not notice, that they have themselves been pointed-at traditional institutions and values; in a context where creativity is akin to subversion, where successful destruction of approved targets is applauded, and accorded high status and material support. For instance, in the post-1945 era and increasingly, positive depictions of extramarital or unconventional sex, drug-taking and criminality were given publicity and elite status; while mockery or subversion of Christian, ‘Bourgeois’ or Middle Class values was similarly applauded.

In sum, modern creatives are highly likely to be amateur or professional, intentional or accidental destroyers of the Good – in their net effect if not wholly. This is one of the horrors of our uniquely nihilistic world.

Humans have always failed to attain The Good due to our own weaknesses and bad motivation – but we are now in the situation where it is normal (also legally and officially encouraged and rewarded) actively to attack The Good, by many means and on many fronts – so that both creative ability and hard-working conscientiousness do not merely fail to reach their promise and their ideals – but are harnessed to work against The Good.

In sum, most modern creatives inflict either more, or less, harmful outcomes overall; and the more effective their creativity, the greater the harm they inflict.
