# What to do

Throughout this book, we seem to have evolved such a distinctive perspective on the nature and effect of Genius, and proposed so many new and unfamiliar ideas, that we can hardly suppose that anyone else would be likely to hold exactly identical views. Most people will therefore need to regard this book as a set of stimuli for further thought and appraisal (or, a collection of what Marshall McLuhan used to call ‘probes’).

In the end we harbour some ambivalence about the place of genius in the modern world. In a rotten and corrupt society, genius is probably more likely to lead to harm than good, for the same reason that any machine will usually do more harm than good when put into the hands of a wicked or stupid person.

But on the other hand, the work of genius is the only realistic hope of Western Man escaping a catastrophic outcome in a society far advanced on the road to ruin; because only the genius can make the qualitative creative leap to discover paths and options invisible to the normal man.

This may be a matter of creating new methods, but perhaps what modern Man most needs is not better means to an end; but a restored sense of the meaning, purpose, reality and community of life. What we lack most of all is motivation – and if a modern genius, or group of geniuses, could somehow create a new basis for motivation – then this would perhaps do more than anything else to improve the prospects of a better future.

1. The modern world has been necessarily based on the work of a concentration of European geniuses from the Middle Ages and into the middle twentieth century; but genius has been disappearing rapidly over the past century, and appears to be extinct in several domains. There exists a state of Genius Famine.

2. This situation has been partly caused, and partly exacerbated by the (seemingly irrational, but sociologically explicable) fact that the modern world has become (and is becoming more) hostile to the Endogenous personality who is the potential basis for genius, and even to the work of actual geniuses; so that the relatively few geniuses who emerge are nowadays usually kept from having any chance of significant influence.

3. On the one hand there is a ‘famine’ of genius – which afflicts science, technology, the arts, politics, philosophy, law... pretty much everything; with very few people of even potential or partial genius now working within these fields. Yet, on the other hand, within these fields, among professionals and experts, there is near-zero awareness, and indeed vehement denial of the blatantly obvious, rapid, and near total decline in genius.

4. Obscuration of the true state of things has been achieved by two opposite (and contradictory) strategies – denying that there is such a thing as real genius, and re-labelling non-creative fake, novelty-cobblers as real geniuses – using mechanisms such as awarding them ‘genius’ prizes or by redefining merely fashionable novelties as examples of genuine creative excellence.

5. Modern people are of considerably lower average and peak ‘general intelligence’ than in the past – so such geniuses as emerge will generally be figures of lesser scope and creative impact than in the past. And insofar as the generation upon generation decline of genius is due to an accumulation of deleterious genetic mutations (caused by the relaxation of natural selection, especially via child mortality) then this would also be expected to damage the evolved and adaptive personality complex of the Endogenous personality.

6. So future geniuses will be lesser figures than in the past: less able, less inner-directed and inner-motivated, with less effective inner-evaluations, and demonstrating less independence and commitment in their creativity.

7. However, even a ‘local genius’, a minor figure by world-historical standards, still provides the _possibility_ of a genuinely creative answer to real problems. No geniuses – no such possibilities.

So, what can we do about all this? How can we improve the situation with respect to geniuses?

Probably there is not much we can do as individuals – indeed, probably the problem of the decline of genius cannot be _solved_, even if there were awareness and understanding of the problem and the determined will to solve it: which there is not.

The only solutions that have been seriously proposed would, in our view, simply not work. Sir Francis Galton (1822-1911) highlighted the problem of the less intelligent outbreeding the more intelligent in Victorian England in his 1869 book _Hereditary Genius_.[113] Later, he argued that this could be solved by a programme of eugenics which would financially incentivise the more intelligent to have the most children combined with inculcating people with a kind of latter-day religiosity which emphasized the importance of improving the ‘human stock.’[114] Others, such as Richard Lynn in his book _Eugenics: A Reassessment_[115] have defended Galton but provided more detail, for example advocating licensing to have children with the permitted number dictated by the couple’s intelligence level.

However, even leaving aside religious prohibitions; it seems to us that there are a number of serious practical problems with these views. Limiting the fertility of the majority of the population in this way could only be achieved in a stringent dictatorship based around, as Galton suggested, some form of ‘secular religion’ of eugenics. This would entail a society of conformity and coercion, which could potentially be highly problematic for generating new ideas or correcting wrong ideas. It is quite possible that such policies would result in protest, rebellion and war, potentially worsening living conditions. Indeed, the toughest problem, and the greatest controversy, would probably come from trying to make the modern secular elites have (on average) above-replacement numbers of children, since all over the world the fertility of those of highest intelligence and most education has fallen very low as soon as contraception has become available.

Moreover, as we have shown, dysgenics on intelligence is caused not just by dysgenic breeding but also, and probably mainly, by mutation accumulation. Accordingly, the only way, if we follow Galton, to reverse dysgenics would be (at minimum) the monstrous policy of allowing to die, to sterilize, or (most effectively) inflict death upon, about half of the children born in each generation.

In other words, effective eugenics would entail Man artificially restoring the pre-modern harshness of natural selection; and thereby reversing what could regarded the single greatest triumph of the Industrial Revolution (which, arguably, has been the near elimination from modern human experience of what used to be the almost universal tragedy of parents suffering the premature death of several or most of their children).

So in practice we would not be likely to do more than merely somewhat ameliorate the genius famine.
On the whole it seems that we should simply do our best to find, support and take notice of genius: to make the most of what genius yet remains.

The hope is that geniuses, by the fact of their genuine creativity, would be our best, and perhaps our _only_, chance of finding an escape route from a trajectory which – by conventional analysis – appears certainly to be terminal for Western civilization.
