# In Search of the Boy Genius

If there was a sense of real crisis, and urgent sense of need, there might emerge a better and more wide-spread ‘search process’ for discovering geniuses: a more effective way of unearthing more individuals from the declining pool of potential geniuses and giving them a better chance of coming-through to a position where they might attain the best work of which they were capable – and then taking some notice of it.

Our description of the Endogenous personality throughout this book would, we hope, make possible and effective this search process: for perhaps the first time, people in search of potential geniuses would know what it was they were looking for – the combination of inner motivation and intuitive thinking with high intelligence.
They would also know what they were not looking for: the empathic, sociable, conscientious, popular and balanced ‘Head Girl’ type, who, despite his or her many virtues and general valuableness – is the opposite of a genius.

Yet, even to write that paragraph is to see that it will likely not happen, and also perhaps why it will not happen. How could a society which is root-and-branch hostile to exactly the kind of person who might (but perhaps won’t) eventually become a genius then make a breakthrough of genius impact, do anything effective to find, nurture and support geniuses? Our society typically sees the actually-existing genius as a problem to be eliminated, rather than the best, and perhaps only, only hope of civilizational salvation.

And there is the paradox of organizing society to encourage the emergence of the disorganized and disorganizing and disruptive. But if something of the sort was actually put into effect (and this might well be a plot for a science fiction novel, perhaps by Philip K Dick), then it could happen by means of a program of psychological profiling and deep aptitude testing by ‘genius masters’ rather like the process which already exists for discovering talent in musical performance – the ways of discovering a great concert pianist or an operatic soloist, or chess grandmasters. That is, a multitude of individual coaches, teachers and Maestros would seek-out and take-on promising youngsters for training; and there would be a variety of exhibitions and competitions aimed at evaluating both achieved performance and (more important) potential.

The Endogenous personality is, in fact, usually detectable from around school age; in his three aspects of high intelligence, intuitive thinking and inner motivation. Intelligence can be tested, with fair reliability and validity; intuitive thinking may be discerned by sympathetic observation of dreaminess and inspired insights; inner motivation will emerge in eccentric and individualistic patterns of interests and behaviours. Armed with this knowledge it is, in principle, quite possible to pick-out the Boy Genius type (including a minority of girls) and help to smooth his path, and recognize his distinctive needs and vulnerabilities.

The framework is that talent-with-potential (typically, high technical ability in a context of the Endogenous personality) is being discovered then developed to a point where the talent can take-over its own development. The apprentice would need to find, and trust, a Master (who would himself need to be an Endogenous personality). The Master would need to want to find, and work with, the best apprentices. And the Masters would be in control of the system (not Head Girls or bureaucrats or committees). Because only the Masters can perceive what is going-on – can perceive the difference between mere high ability and the potential for creative genius. But aside from that, there is no ‘system’. No formal requirements. No standard progression. No accreditation of any significance.

But it is equally, perhaps more, essential that the potential genius be given the kind of personal and emotional support he needs – or at least that he be not assaulted by what he would perceive as additional stresses. Many (not all) geniuses are (as Ruskin perceived, and knew from personal experience) unusually childlike and dependent; and benefit from a higher level and greater duration of ‘looking after’ – which would typically come from the family, but if not them then someone else trustworthy, caring, and with the genius’s best interests at heart. The sad experience of William Sidis – thrown by his parents, still a child-like child, into the rough turmoil of Harvard – should be a warning in this regard.

The above may sound all too privileged for the already-privileged, terribly elitist, very esoteric. It is a statement of the need for special treatment for special people. And it sees talent and the potential for genius as essentially innate. If you haven’t got it you can’t do it; and if even you have, you probably won’t. It asks for everything that modern culture despises, and indeed regards as immoral.

Furthermore, this is anti-democratic, anti-popular, and aristocratic. High intellectual ability is itself very rare, but high ability in the context of an Endogenous personality is rarer still. The process of finding Boy Geniuses is about searching for a very few diamonds among great heaps of (useful) coal – but with a distracting and deceptive proportion of gaudy ‘costume jewellery’ (pretend diamonds, pseudo-geniuses) taking the form of un-creative skill and fake creativity.

In conclusion, if modern society was concerned with its own continuation – which very clearly it is not, being instead self-loathing and covertly devoted to its own extinction – then something of this kind would need to occur to locate and empower sufficient numbers of geniuses to maintain the frequent and relevant breakthroughs necessary to enable continued growth in efficiency and capability.

But, overall, it seems that we have to accept that Western civilization will decline. It is, essentially, inevitable. Life will go backwards, life will become simpler, harsher – much less comfortable, much more serious.

Eventually, and after considerable suffering; like it or not; perhaps enough people will come to feel part of groups, to see the benefits of genius to the group, and to recognize the necessity of genius.

And the genius will again resume his proper role in society.
