# Conclusion: Seven statements about genius {.unnumbered}

1. We need to recognize that support for genius is social self-interest – it is a risky investment, true; but when it pays off, a genius yields vastly more benefit than he costs.

2. The benefits yielded by genius are not obtainable in any other way.

3. Genius is born and not made. Training of non-geniuses will not yield more geniuses.

4. Genius can be identified, and may be encouraged and flourish; or alternatively genius can be ignored, thwarted, suppressed – and rendered irrelevant.

5. A genius is a difficult, eccentric, asocial person who – despite this – exists in order to promote the good of the group.

6. Yet, although strong in self-motivation, self-determination and autonomy – a genius is normally a sensitive and emotionally vulnerable person. He can be dismayed, demoralized, corrupted or driven to despair – and his potential will then be diminished or destroyed.

7. In future most genius will be ‘local’ (by our current standards), rather than international: a shaman rather than an Einstein. This is the best that can realistically be hoped-for – but a local genius is better than no genius at all.
